.vscode/settings.json
typescript/package-lock.json
typescript/packages/basic-ifc/package.json
typescript/packages/basic-ifc/src/ifc.ts
typescript/packages/basic-ifc/src/ifc_test.ts
typescript/packages/basic-ifc/src/index.ts
typescript/packages/basic-ifc/tsconfig.json

Basic IFC implementation in progress

Basic IFC in TS

---

typescript/packages/common-frp/src/operators.ts
typescript/packages/common-frp/src/signal.ts

Update computed signature to include any case

---

typescript/packages/common-frp/src/index.ts

...allows flagging on debug for detailed transaction information.

Export config

---

typescript/packages/basic-ifc/src/guardrails_test.ts
typescript/packages/basic-ifc/src/validator.ts
typescript/packages/basic-ifc/src/validator_test.ts

Documenting all the possible constraints that follow from recipes and module manifests. Most are yet to be implemented.

Documenting Validation algorithm

---

typescript/packages/common-frp/src/dom.ts
typescript/packages/common-frp/src/signal.ts
typescript/packages/common-frp/src/stream.ts

...Symbols don't actually give us private/protected members :(
https://esdiscuss.org/topic/proposal-about-private-symbol

Replace symbols with names in FRP

---

typescript/packages/common-ui/src/components/datatable.ts
typescript/packages/common-ui/src/components/dict.ts
typescript/packages/common-ui/src/components/hstack.ts
typescript/packages/common-ui/src/components/navpanel.ts
typescript/packages/common-ui/src/components/record.ts
typescript/packages/common-ui/src/components/vstack.ts
typescript/packages/common-ui/src/example.ts
typescript/packages/common-ui/src/hyperscript/tags.ts
typescript/packages/common-ui/tsconfig.json

Some basic UI components

---

typescript/packages/common-frp/src/signal.ts
typescript/packages/common-frp/src/stream.ts

...defined as interfaces, not classes.

Add isSignal and isStream

---

typescript/packages/common-ui/src/components/send-input.ts
typescript/packages/common-ui/src/hyperscript/render.ts
typescript/packages/common-ui/src/hyperscript/tags.ts
typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/suggestion.ts

sends an `input` event with `data: <value>` and clears the input box when the user taps the button.

Common UI send input component

---

typescript/packages/common-ui/src/components/include.ts
typescript/packages/common-ui/src/components/send-input.ts
typescript/packages/lookslike-high-level/src/components/annotation.ts
typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/main.ts
typescript/packages/lookslike-high-level/src/recipe.ts
typescript/packages/lookslike-high-level/src/recipes/annotation.ts
typescript/packages/lookslike-high-level/src/recipes/todo-list-as-task.ts
typescript/packages/lookslike-high-level/src/recipes/todo-list.ts
typescript/packages/lookslike-high-level/src/suggestion.ts

- shows suggestion to refer to grocery list
- renders it inline as summary and expanded view
- toggling all items as done sets parent task to done

Lookslike todo with "AI" suggestions and nested recipes

---

typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/main.ts
typescript/packages/lookslike-high-level/src/recipes/recipe-list.ts

List all available recipes on the home screen

---

typescript/packages/common-ui/src/components/common-input.ts
typescript/packages/common-ui/src/components/common-todo.ts

Allows adding content underneath todo.

Add slot to todo items

---

typescript/packages/common-ui/src/components/common-hscroll.ts
typescript/packages/common-ui/src/components/index.ts
typescript/packages/lookslike-sagas/index.html

...creates a horizontal scroller for many items

Add hscroll

---

rust/usuba/src/openapi.rs
rust/usuba/src/routes/mod.rs
rust/usuba/src/routes/verify/mod.rs
rust/usuba/src/serve.rs
typescript/packages/common-verifier/src/service-worker.ts

...to query runtime as HTTP HEAD on well known route for a lookslike-prototype.

Wire verification extension to lookslike-prototype verification

---

typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/recipes/annotation.ts
typescript/packages/lookslike-high-level/src/recipes/home.ts
typescript/packages/lookslike-high-level/src/recipes/luft-bnb-search.ts
typescript/packages/lookslike-high-level/src/recipes/reservation.ts

Creates this suggestion:
After click, shows link to full search and shortcut to book first result:

suggest luftbnb search based on reservation

---

.gitignore
typescript/packages/linkheap/.env.local
typescript/packages/linkheap/README.md
typescript/packages/linkheap/deps.ts
typescript/packages/linkheap/main.ts
typescript/packages/linkheap/package.json
typescript/packages/linkheap/tsconfig.json

Link clipping playground. Save links to collections, scrape the markup and do some basic LLM analysis.
Then, generate views of the various collections!

linkheap Prototype

---

typescript/packages/linkheap/main.ts

- most (but not all) logging is now done by the cli main function
- throw errors rather than logging (except in main)
- use json destructuring of sql results rather than list style results

tweak logging/destructuring/io to simplify building api/ui around

---

typescript/packages/lookslike-high-level/src/builder/index.ts
typescript/packages/lookslike-high-level/src/builder/module.ts
typescript/packages/lookslike-high-level/src/recipes/luft-bnb-search.ts
typescript/packages/lookslike-high-level/src/recipes/playlist.ts
typescript/packages/lookslike-high-level/test/runner/html-recipes.test.ts

Examples:
- generateData({ prompt: str`hello ${name}` })
- return { [NAME]: str`Booking for ${place.location}`

str`` helper to create reactive strings that reference cells

---

typescript/packages/common-builder/src/built-in.ts
typescript/packages/common-builder/src/index.ts
typescript/packages/common-runner/src/builtins/fetch-data.ts
typescript/packages/common-runner/src/builtins/index.ts
typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/recipes/fetchExample.ts

[WIP] FEAT: for fetchData based on generateData

---

typescript/packages/lookslike-high-level/src/components/window-manager.ts

sagas.map was removing the wrong element from the list
fixes #142

using lit repeat to fix closing bug

---

typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/recipes/counter.ts

count is a complex object due to bug #144

add counter example

---

typescript/packages/collectathon/chrome-extension/popup.js
typescript/packages/collectathon/server.ts
typescript/packages/collectathon/view.ts

- port 8000 -> 8001
- don't leave server running if you ctrl-c

collectathon collected tweaks?

---

typescript/packages/common-builder/src/index.ts
typescript/packages/common-runner/src/builtins/generate-data.ts
typescript/packages/lookslike-high-level/src/components/iframe-view.ts
typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/recipes/dungeon.ts
typescript/packages/lookslike-high-level/src/recipes/fetchCollections.ts
typescript/packages/lookslike-high-level/src/recipes/iframeExample.ts
typescript/packages/lookslike-high-level/src/recipes/importCalendar.ts

- **More resilient to LLM postMessage use**
- **Add schema, react, tailwind support to iframes**
- **Hack things into place for the demo**

iframes support Tailwind + React for calendar demo

---

typescript/packages/planning-server/README.md

- resolves https://github.com/commontoolsinc/labs/issues/180

docs: update README with CI and deployment details for Planning Server

---

typescript/packages/lookslike-high-level/src/recipes/counter.ts
typescript/packages/lookslike-high-level/src/recipes/counters.ts

This fixes the demo, but of course means we still have a bug with literals at a higher level.

fix counters by nesting value

---

typescript/packages/common-runner/src/builtins/fetch-data.ts
typescript/packages/common-runner/src/builtins/generate-data.ts
typescript/packages/common-runner/src/builtins/if-else.ts
typescript/packages/common-runner/src/cell.ts
typescript/packages/common-runner/src/index.ts
typescript/packages/common-runner/src/runner.ts
typescript/packages/common-runner/src/utils.ts
typescript/packages/common-runner/test/runner.test.ts
typescript/packages/common-runner/test/utils.test.ts
typescript/packages/lookslike-high-level/src/components/recipe-link.ts

Various minor fixes for elements are cells

---

typescript/packages/lookslike-high-level/src/components/recipe-link.ts
typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/recipes/home.ts

Minor cleanup that doubles as preparation to hash-based recipe addressing

Open recipes via ids

---

typescript/packages/lookslike-high-level/src/components/window-manager.ts
typescript/packages/lookslike-high-level/src/main.ts
typescript/packages/lookslike-high-level/src/recipes/annotation.ts

Make sure string versions of entity ids are all derived from json version

fix: consistently use JSON.stringify() for entities ids

---

typescript/packages/common-runner/src/runner.ts
typescript/packages/lookslike-high-level/src/data.ts

This should happily collide with already stored ones, once we have persistence.

Feature: Make cell ids more causal, in particular the ones created on startuo

---

typescript/packages/common-builder/src/recipe.ts
typescript/packages/lookslike-high-level/src/recipes/prompts.ts

sending a string maintains the flow of constructing from inputs

allow recipes to send their schema

---

typescript/packages/common-html/src/index.ts
typescript/packages/common-html/src/jsx.ts
typescript/packages/common-html/src/render.ts
typescript/packages/lookslike-high-level/src/recipes/counters.tsx
typescript/packages/lookslike-high-level/src/recipes/prompts.tsx
typescript/packages/lookslike-high-level/tsconfig.json

- generate a vnode vdom using jsx
- common-html render updates to support raw render of vdom
- update recipes to typescript

jsx support

---

typescript/packages/common-os-ui/index.html
typescript/packages/common-os-ui/src/components/os-sidebar-group.ts

Allows sidebar group to opt into padding for content.

Add safearea styling to sidebar group

---

typescript/packages/common-html/src/render.ts
typescript/packages/lookslike-high-level/src/components/charm-link.ts
typescript/packages/lookslike-high-level/src/components/common-draggable.ts
typescript/packages/lookslike-high-level/src/components/common-droppable.ts
typescript/packages/lookslike-high-level/src/components/index.ts
typescript/packages/lookslike-high-level/src/components/window-manager.ts
typescript/packages/lookslike-high-level/src/recipes/home.ts
typescript/packages/lookslike-high-level/src/recipes/todo-list.tsx

Implements drag'n'drop as described in #236 in framework and todo list

Add drag n drop

---

typescript/packages/common-runner/src/index.ts
typescript/packages/common-runner/src/recipe-map.ts
typescript/packages/lookslike-high-level/src/components/sidebar.ts
typescript/packages/lookslike-high-level/src/data.ts
typescript/packages/lookslike-high-level/src/recipes/counters.md
typescript/packages/lookslike-high-level/src/recipes/index.ts

This PR wires up recipe specs through the sidebar, recipe-map, and also introduces a quick approach to setting a spec of a recipe via markdown in the counters recipe.

Sidebar recipe specs

---

typescript/packages/common-runner/src/builtins/map.ts

pair with @seefeldb on rewriting how map works to fix issues @jakedahn hit around "init" generating non-cells.
This is progress towards the refactoring work that @seefeldb has been leading

rewrite of how map works

---

typescript/packages/common-ui/src/components/common-hstack.ts
typescript/packages/common-ui/src/components/common-textarea.ts
typescript/packages/common-ui/src/components/common-vstack.ts
typescript/packages/common-ui/src/components/index.ts
typescript/packages/common-ui/src/components/style.ts
typescript/packages/lookslike-high-level/src/recipes/counter.tsx
typescript/packages/lookslike-high-level/src/recipes/counters.tsx
typescript/packages/testkitchen/evals/codegen-firstrun/02-wedding-seating-chart/original-spec.md
typescript/packages/testkitchen/evals/codegen-firstrun/02-wedding-seating-chart/original.tsx
typescript/packages/testkitchen/prompts.ts

incremental progress on evals, improvements to `<common-hstack>`, `<common-vstack>`, and some updates to `counters.tsx` with the latest syntax

Testkitchen wedding scenario

---

typescript/packages/common-charm/src/storage-providers.ts
typescript/packages/common-memory/lib.ts
typescript/packages/lookslike-high-level/vite.config.ts
typescript/packages/toolshed/app.ts
typescript/packages/toolshed/deno.json
typescript/packages/toolshed/deno.lock
typescript/packages/toolshed/lib/create-app.ts
typescript/packages/toolshed/routes/ai/img/img.index.ts
typescript/packages/toolshed/routes/ai/llm/llm.index.ts
typescript/packages/toolshed/routes/ai/spell/spell.index.ts
typescript/packages/toolshed/routes/ai/voice/voice.index.ts
typescript/packages/toolshed/routes/ai/webreader/webreader.index.ts
typescript/packages/toolshed/routes/integrations/discord/discord.index.ts
typescript/packages/toolshed/routes/storage/blobby/blobby.index.ts
typescript/packages/toolshed/routes/storage/memory/memory.handlers.ts
typescript/packages/toolshed/routes/storage/memory/memory.index.ts
typescript/packages/toolshed/routes/storage/memory/memory.routes.ts
typescript/packages/toolshed/routes/storage/memory/memory.test.ts

Fixes memory store routing with hone, at least tests seem to pass on my device and CI now.

Storage memory toolshed integration

---

typescript/packages/common-iframe-sandbox/README.md
typescript/packages/common-iframe-sandbox/src/common-iframe-sandbox.ts
typescript/packages/common-iframe-sandbox/src/csp.ts
typescript/packages/lookslike-high-level/src/data.ts

Fix serialization of proxy objects when communicating with iframe. Extend docs.

chore: Clean up common-iframe-sandbox

---

typescript/packages/common-charm/src/storage-providers.ts

remote provider was sending WAY too many patches
addresses #320

only send PATCH when value changes

---

typescript/packages/common-charm/src/iframe/recipe.ts
typescript/packages/common-charm/src/index.ts
typescript/packages/common-charm/src/iterate.ts
typescript/packages/common-ui/src/components/index.ts
typescript/packages/jumble/src/components/CharmRunner.tsx
typescript/packages/jumble/src/components/CommandCenter.tsx
typescript/packages/jumble/src/components/NavPath.tsx
typescript/packages/jumble/src/views/CharmList.tsx
typescript/packages/lookslike-high-level/src/recipes/todo-list.tsx

- command-k `Load Recipe` to add a non-iframe recipe
- rendering uses effects to connect to the vdom in a reactive way

Load recipe command

---

typescript/packages/common-charm/src/iframe/prompt.ts
typescript/packages/common-charm/src/iterate.ts
typescript/packages/jumble/src/components/CommandCenter.tsx
typescript/packages/jumble/src/components/DitherCube.tsx
typescript/packages/jumble/src/components/commands.css
typescript/packages/jumble/src/components/commands.ts
typescript/packages/jumble/src/contexts/LanguageModelContext.tsx
typescript/packages/jumble/src/main.tsx
typescript/packages/lookslike-high-level/src/components/spell-ai.ts

- **Style command palette to fit hypercard theme**
- **Refactor command palette** (`commands.ts`)
- https://github.com/commontoolsinc/labs/issues/370
- https://github.com/commontoolsinc/labs/issues/371
- https://github.com/commontoolsinc/labs/issues/372
- https://github.com/commontoolsinc/labs/issues/373
- https://github.com/commontoolsinc/labs/issues/374

Jumble: New Commands

---

typescript/packages/jumble/src/components/AudioRecorderInput.tsx
typescript/packages/jumble/src/components/CommandCenter.tsx
typescript/packages/jumble/src/components/DitherCube.tsx
typescript/packages/jumble/src/components/TranscribeCommand.tsx
typescript/packages/jumble/src/components/commands.ts
typescript/packages/jumble/src/hooks/use-audio-recorder.ts
typescript/packages/jumble/src/views/CharmDetailView.tsx

- **Port audio transcription component from list to a react hook**
- **Add transcription as a possible command type**
- **New Iterate (Voice) command**
- **Close palette after iteration complete**
- **Add loading spinner to Iterate panel**
https://github.com/user-attachments/assets/147a89ce-083c-46ed-aa57-e187b1b4ebb8

Iterate Flow: Voice Input

---

typescript/packages/jumble/src/components/VariantTray.tsx
typescript/packages/jumble/src/utils/prompt-library/charm-describe.ts
typescript/packages/jumble/src/utils/prompt-library/charm-suggestions.ts
typescript/packages/jumble/src/utils/prompt-library/prompting.ts
typescript/packages/jumble/src/views/CharmDetailView.tsx

This PR adds suggestions to the charm iteration mode
When a suggestion is clicked, we generate 3 variants with different language models

Charm suggestions

---

typescript/packages/jumble/src/components/Card.tsx
typescript/packages/jumble/src/views/CharmList.tsx

- fixes #413 
https://github.com/user-attachments/assets/08c013ba-011c-4542-8ce9-44ba428c28de

Render semi-interactive charm preview in main feed

---

typescript/packages/jumble/src/views/CharmDetailView.tsx

Render actual charm input and result data in UI

---

typescript/packages/jumble/src/contexts/LanguageModelContext.tsx
typescript/packages/jumble/src/iframe-ctx.ts
typescript/packages/jumble/src/utils/charm-operations.ts
typescript/packages/jumble/src/utils/prompt-library/recipe-fix.ts
typescript/packages/jumble/src/utils/prompt-library/recipe-guide.ts

This PR removes our usage of `groq:llama-3.3-70b-specdec`, and swaps to `groq:llama-3.3-70b-versatile`, due to context length limitations.
Also improves our fixit prompt, while swapping over to gemini 2.0 pro

Improving fixit and friends

---

typescript/packages/common-memory/socket.ts

Handle socket.close() TypeError

---

typescript/packages/common-charm/src/syncRecipe.ts
typescript/packages/jumble/package.json
typescript/packages/jumble/src/components/ShellHeader.tsx
typescript/packages/jumble/src/components/spellbook/ActionButton.tsx
typescript/packages/jumble/src/components/spellbook/SearchBox.tsx
typescript/packages/jumble/src/components/spellbook/ShareDialog.tsx
typescript/packages/jumble/src/components/spellbook/SpellCard.tsx
typescript/packages/jumble/src/components/spellbook/SpellPreview.tsx
typescript/packages/jumble/src/components/spellbook/SpellbookHeader.tsx
typescript/packages/jumble/src/hooks/use-debounce.ts
typescript/packages/jumble/src/main.tsx
typescript/packages/jumble/src/services/blobby.ts
typescript/packages/jumble/src/services/spellbook.ts
typescript/packages/jumble/src/utils/api.ts
typescript/packages/jumble/src/views/CharmList.tsx
typescript/packages/jumble/src/views/spellbook/SpellbookDetailView.tsx
typescript/packages/jumble/src/views/spellbook/SpellbookIndexView.tsx
typescript/packages/jumble/src/views/spellbook/SpellbookLaunchView.tsx
typescript/packages/jumble/vite.config.ts
typescript/packages/pnpm-lock.yaml
typescript/packages/spellbookjr/app/components/recipe-detail.tsx
typescript/packages/toolshed/app.ts
typescript/packages/toolshed/routes/spellbook/spellbook.handlers.ts
typescript/packages/toolshed/routes/spellbook/spellbook.index.ts
typescript/packages/toolshed/routes/spellbook/spellbook.routes.ts
typescript/packages/toolshed/routes/whoami/whoami.handlers.ts
typescript/packages/toolshed/routes/whoami/whoami.index.ts
typescript/packages/toolshed/routes/whoami/whoami.routes.ts

This pull request introduces the Spellbook.
Spellbook is a central repository of spells that users have published. It's a great place to find new spell ideas, get inspiration from the community, and even share your own ideas.

Spellbook sr

---

typescript/packages/jumble/src/services/spellbook.ts
typescript/packages/jumble/src/views/spellbook/SpellbookDetailView.tsx
typescript/packages/toolshed/routes/spellbook/spellbook.handlers.ts
typescript/packages/toolshed/routes/spellbook/spellbook.index.ts
typescript/packages/toolshed/routes/spellbook/spellbook.routes.ts
typescript/packages/toolshed/routes/storage/blobby/blobby.handlers.ts
typescript/packages/toolshed/routes/storage/blobby/blobby.index.ts
typescript/packages/toolshed/routes/storage/blobby/blobby.routes.ts
typescript/packages/toolshed/routes/storage/blobby/lib/redis.ts
typescript/packages/toolshed/routes/storage/blobby/lib/storage.ts

This pr adds the ability to delete blobby blobs, and also spellbook spells

Introducing blobby and spellbook deletes

---

typescript/packages/common-charm/src/charm.ts
typescript/packages/jumble/src/views/CharmList.tsx

adds a delete icon on hover that will remove the charm

enable deletion of charms

---

typescript/packages/common-charm/src/charm.ts
typescript/packages/common-charm/src/iframe/recipe.ts
typescript/packages/common-charm/src/iterate.ts
typescript/packages/common-charm/src/storage.ts
typescript/packages/common-runner/src/builtins/fetch-data.ts
typescript/packages/common-runner/src/builtins/stream-data.ts
typescript/packages/common-runner/src/cell-map.ts
typescript/packages/common-runner/src/cell.ts
typescript/packages/common-runner/src/query-result-proxy.ts
typescript/packages/common-runner/src/runner.ts
typescript/packages/common-runner/src/utils.ts
typescript/packages/common-runner/test/utils.test.ts
typescript/packages/jumble/src/components/CharmRunner.tsx
typescript/packages/jumble/src/components/NavPath.tsx
typescript/packages/jumble/src/components/ShellHeader.tsx
typescript/packages/jumble/src/components/VariantTray.tsx
typescript/packages/jumble/src/components/commands.ts
typescript/packages/jumble/src/contexts/CharmManagerContext.tsx
typescript/packages/jumble/src/hooks/use-cell.ts
typescript/packages/jumble/src/hooks/use-charm.ts
typescript/packages/jumble/src/utils/charm-operations.ts
typescript/packages/jumble/src/utils/charms.ts
typescript/packages/jumble/src/utils/indexing.ts
typescript/packages/jumble/src/views/CharmDetailView.tsx
typescript/packages/jumble/src/views/CharmList.tsx

replaced all instances of DocImpl with Cell in React and CharmManager interface
and various small helper changes for that

Replace all uses of raw documents with `Cell` in Jumble

---

typescript/packages/common-html/src/render.ts

Effect supports both static data and Cells, so it'll just run through this once for static data
(Inspired by comment in #443 asking about using childValue)

simplify renderChild by deduping cell and non-cell path

---

typescript/packages/common-identity/src/ed25519/native.ts
typescript/packages/common-identity/src/key-store.ts
typescript/packages/common-identity/src/utils.ts
typescript/packages/common-identity/test/key-store.test.js
typescript/packages/jumble/src/contexts/AuthenticationContext.tsx
typescript/packages/jumble/src/views/AuthenticationView.tsx

This fails in Firefox < 136, so fallback to using noble ed25519 implementation

feat: Test if ed25519 keys can be stored in IndexedDB before using native ed25519 keys

---

typescript/packages/jumble/src/components/commands.ts
typescript/packages/toolshed/routes/ai/spell/behavior/effects.ts
typescript/packages/toolshed/routes/ai/spell/spell.handlers.ts

https://github.com/user-attachments/assets/562953e4-fbed-4624-862f-030287902b13
- Introduce command to re-use the current charm's spell on another compatible piece of data.

Implement spell re-casting endpoint + command

---

typescript/packages/common-charm/src/storage.ts
typescript/packages/common-html/src/logger.ts

so we don't serialize data all the time when debugging if off

storage: log via callback

---

typescript/packages/common-charm/src/storage.ts
typescript/packages/common-runner/src/runner.ts

alternative way to fix the bug where syncing a frozen cell causes an error when changing it

don't send data to frozen cells

---

typescript/packages/common-cli/main.ts

... just because I got that wrong this morning and this would have saved me a lot of time.

chore: log cli parameters in console

---

typescript/packages/common-charm/src/charm.ts
typescript/packages/common-charm/src/index.ts
typescript/packages/common-cli/google-importer.ts
typescript/packages/common-cli/main.ts
typescript/packages/common-runner/src/index.ts
typescript/packages/common-runner/src/recipe-sync.ts

so storage and this are together

chore: moved recipe saving to runner

---

.vscode/extensions.json

switch from recommending prettier to recommending deno

.vscode/extensions.json

---

typescript/packages/common-runner/src/storage.ts

measure time from end of transaction, not beginning, so we're debouncing based on enough time _between_ transactions (previously this worked for localstorage, which was just fast enough to not trigger this issue)

fix: storage correctly debouncing too rapid storage requests

---

typescript/packages/common-memory/deno.json
typescript/packages/common-memory/test/space-test.ts
typescript/packages/common-memory/test/stress-debug.ts

I don't know when this regression was introduced but this fixes the type checking in memory package @jsantell do you mind showing me how to enable it in ci

fix: type checking

---

typescript/packages/common-cli/gmail.tsx
typescript/packages/common-ui/src/components/common-google-oauth.ts
typescript/packages/toolshed/routes/integrations/google-oauth/google-oauth.handlers.ts
typescript/packages/toolshed/routes/integrations/google-oauth/google-oauth.utils.ts

clean up the button a bit and store user info

Google import fixes

---

typescript/packages/jumble/src/components/commands.ts

Not yet using result schema, that will make life much easier.
https://github.com/user-attachments/assets/bf75c825-c99e-46c3-93fa-8bd683f11cf4

Add 'Execute Charm Action' command

---

typescript/packages/common-memory/deno.json
typescript/packages/common-memory/lib.ts
typescript/packages/common-memory/memory.ts
typescript/packages/common-memory/socket.ts
typescript/packages/common-memory/space.ts
typescript/packages/common-memory/telemetry.ts
typescript/packages/deno.lock
typescript/packages/toolshed/.env.example
typescript/packages/toolshed/deno.json
typescript/packages/toolshed/env.ts
typescript/packages/toolshed/index.ts
typescript/packages/toolshed/lib/create-app.ts
typescript/packages/toolshed/middlewares/opentelemetry.ts
typescript/packages/toolshed/routes/storage/memory/memory.handlers.ts

This PR adds instrumentation and tracing to common-memory and toolshed

OpenTelemetry for toolshed + common-memory

---

README.md
cli/notes.ts
deno-web-test/README.md
identity/README.md
iframe-sandbox/README.md
memory/README.md
scripts/test-all.ts
toolshed/Dockerfile
toolshed/README.md
toolshed/deploy/toolshed.nginx.conf
toolshed/deploy/toolshed@.service

This PR is follow-up to https://github.com/commontoolsinc/labs/pull/565 to update the docs and bring the latest toolshed configuration files up to date'

Reorg followup

---

jumble/src/components/CommandCenter.tsx
jumble/src/components/commands.ts

https://github.com/user-attachments/assets/d5848713-5d26-4abb-ab2a-18c081c5d56a

Add "Open in Stack" command

---

charm/src/iframe/static.ts
runner/src/utils.ts

disable normalizeToDocLinks(parentDoc, value, undefined, log, cause);
> build "common bug tracker" that lets you enter bugs as post it notes and assign them to a person.  each person is a tab.  Tony, Jesse, Jake, Alex, Robin, Ben, Irakli, Jordan, Berni, Ellyse

workaround that will need revisited

---

jumble/src/main.tsx

until we redo the react context managers we shouldn't navigate between charms

redirect to replica using location.href

---

charm/src/iterate.ts
deno.jsonc
llm-client/src/index.ts
runner/src/llm-client.ts
runner/src/storage.ts
utils/deno.json
utils/src/defer.ts
utils/src/env.ts
utils/src/index.ts

* Previous deno detection was failing.
* Consolidate default LLM URL
* Introduce `@commontools/utils` with env utilities and deferred (used shortly)

Add @commontools/utils, fix environment detection

---

charm/src/iframe/static.ts
iframe-sandbox/src/common-iframe-sandbox.ts
iframe-sandbox/src/context.ts
iframe-sandbox/src/ipc.ts
iframe-sandbox/test/utils.ts
jumble/src/iframe-ctx.ts

Introduce `readWebpage` function that works almost identically to the LLM requests.

Add support for reading webpages

---

charm/src/iframe/static.ts

- **Fix doc comment**
- **Improve legibility of useDoc and handling of defaults**

Improve `useDoc`

---

iframe-sandbox/src/common-iframe-sandbox.ts
jumble/src/components/CharmRunner.tsx
ui/src/components/common-iframe.ts

update css to support displaying iframes and non-frame charms with proper scrolling

better rendering for iframe/non-iframe

---

jumble/src/iframe-ctx.ts
runner/src/cell.ts

This will create individual documents at the storage layer for everything that comes from the Iframe and has an `id` property, and it'll process updates a la DOM diffing, so even if the entire JSON is shipped, it'll only update the documents that changed.

Iframe context translates `id` that React likes to create to our `ID` property

---

charm/src/iterate.ts
runner/src/index.ts
runner/src/recipe-map.ts
runner/src/recipe-sync.ts
runner/src/runner.ts

- **Do not re-create merkle ref every time we try to load a recipe**
- **Refactor addRecipe to registerNewRecipe and registerRecipe**

Speed up recipe sync

---

jumble/integration/basic-flow.test.ts
jumble/integration/utils.ts

.. rather than assume elements are available

chore: Explicitly wait for selectors in integration tests

---

charm/src/iframe/static.ts
iframe-sandbox/src/csp.ts
jumble/src/iframe-ctx.ts

- **ESM imports in iframes**
- **Tweak libraries and prompting**
- **Fix ESM import for libraries using React**

Use ESM for external libraries in iframes

---

jumble/src/components/ShellHeader.tsx
jumble/src/components/User.tsx

https://github.com/user-attachments/assets/812ed8fe-4194-4bc1-8cba-23447eef9cb9

Render current network activity as decoration around User avatar

---

recipes/gmail.tsx

This PR improves the gmail importer in a few ways
* Exports all gmail labels as a result on the gmail integration recipe
* Adds html content to the result on the gmail integration recipe
* Adds the ability to sync multiple labels

Gmail integration improvements

---

cli/google-importer.ts

```
$ TOOLSHED_API_URL=https://toolshed.saga-castor.ts.net \
deno run -A google-importer.ts --charms \
did:key:z6Mkip5BXmURHJjXDLh1gGHdTWrpPvUycoDEGK6jbz1mkawg/baedreibju3vxd6pcaea6ixildgcy4meth65lyadyzi5xshae2td7ds6hbi, \
did:key:z6MkfZmYzcxp4yaQ5H69gYYQDJvLyy1n8TZbSGckz83u44TM/baedreics2iazkycidhuwoyldx4qxwtz75p3vyy3vig7lpiulsnyrp6yrlm
```

feat: update google-importer to accept an array of space/charmId pairs

---

deno.lock
jumble/deno.json
jumble/integration/basic-flow.test.ts
jumble/src/components/CommandCenter.tsx
jumble/src/components/Composer.tsx
jumble/src/utils/format.ts
jumble/src/views/CharmDetailView.tsx

- Composer
- basic markdown support
- @ ref support
- formatting data for inclusion in prompt
This does NOT do anything clever with the data, it just mashes it into a big text blob and sends it to the LLM. We should (and will shortly) synthesize a new schema and argument cell and pas that through into our overall pipeline.

MVP @-referencing and Composer

---

recipes/discord.tsx

Discord recipe

---

jumble/src/components/CharmRunner.tsx

Fix sticky errors on charm previews

---

jumble/src/views/CharmDetailView.tsx

- fixes https://github.com/commontoolsinc/labs/issues/700

Disable variants by default in edit panel

---

builder/test/opaque-ref-schema.test.ts
runner/test/schema-lineage.test.ts

More tests

---

jumble/src/iframe-ctx.ts

Remove subscribe from asterisk noise

---

jumble/src/views/CharmDetailView.tsx

use schema for detail view + sanitize json in case schema defines streams or nested cells

---

toolshed/routes/integrations/google-oauth/google-oauth.handlers.ts

Recent infrastructure changes introduced several load balanced instances of the hono api behind a single web server endpoint. This broke the ability to statelessly validate an oauth token flow.
This PR passes the verifier forward inside the state parameter, and allows us to statelessly verify the response without storing the value intermediately in RAM.

Fixing gmail oauth flow

---

charm/src/charm.ts
charm/src/iterate.ts
jumble/src/components/CharmLink.tsx
jumble/src/components/HoverPreview.tsx
jumble/src/components/NavPath.tsx
jumble/src/hooks/use-cell.ts
jumble/src/hooks/use-charm-hover.ts
jumble/src/views/CharmDetailView.tsx
jumble/src/views/CharmList.tsx

Pretty basic :) Should it do this on other things than iterate?

Save parents when iterating on charm

---

jumble/integration/basic-flow.test.ts
jumble/src/components/CommandCenter.tsx
jumble/src/components/Composer.tsx
jumble/src/views/CharmDetailView.tsx

Improve multi-line support in Composer (+ increase default height)

---

jumble/src/views/CharmDetailView.tsx

Previously, an object that had already been serialized was flagged as a circular reference, but if we've already popped out of that context, we can include it again.
For efficiency, I also store the JSON version of the objects we've completed copying to JSON.

Improve circular reference detection

---

background-charm-service/src/config.ts
background-charm-service/src/service.ts
runner/src/storage.ts
toolshed/env.ts
toolshed/routes/integrations/google-oauth/google-oauth.utils.ts
toolshed/routes/storage/memory.ts
toolshed/routes/storage/memory/memory.test.ts
utils/src/gmail-integration-charms.ts

addresses #766 and #747 ..
this will allow us to deploy production toolshed to hit same router for connecting to toolshed

switch to using different ENV vars for memory remote url vs sqlite path

---

deno.jsonc
deno.lock
html/deno.json
recipes/rss.tsx
runner/src/local-build.ts

atom support for feeds

---

jumble/src/components/CharmTable.tsx
jumble/src/views/CharmList.tsx

- fixes https://github.com/commontoolsinc/labs/issues/795

Restore from trash

---

.vscode/settings.json
deno.jsonc
jumble/deno.json
jumble/src/global.d.ts

Remove `declare module "*"` and enable `skipLibCheck`

Enable `skipLibCheck` and more, remove wildcard `*` types

---

scripts/diagnose.ts

Example output: https://github.com/commontoolsinc/labs/issues/803#issuecomment-2744076483

Create diagnose script

---

jumble/src/components/ShellHeader.tsx
jumble/src/components/User.tsx
jumble/src/views/Shell.tsx
memory/consumer.ts
memory/lib.ts
memory/test/consumer-test.ts
runner/deno.json
runner/src/index.ts
runner/src/storage/inspector.ts
runner/src/storage/remote.ts

- fixes https://github.com/commontoolsinc/labs/issues/729
https://github.com/user-attachments/assets/52fdfd88-2e1a-4df9-a816-349c67e76586

Add model for memory state, update activity indicator

---

.gitignore
scripts/fix-issue.ts

- **Ignore temp files**
- **Fix temp file handling in fix issue**

Fix 'fix-issue' temp files

---

deno.jsonc
deno.lock
jumble/src/components/Inspector.tsx
jumble/src/components/NetworkInspector.tsx
jumble/src/components/User.tsx
jumble/src/components/View.tsx
jumble/src/components/commands.ts
jumble/src/contexts/NetworkInspectorContext.tsx
jumble/src/hooks/use-animation-smoothing.ts
jumble/src/hooks/use-network-inspector.ts
jumble/src/hooks/use-resizeable-drawer.ts
jumble/src/main.tsx
jumble/src/views/CharmDetailView.tsx
jumble/src/views/Shell.tsx
runner/src/storage/inspector.ts

Fixes #714 
https://github.com/user-attachments/assets/5de2a6cc-e31d-443d-8355-d92b384f2e87

Web Socket Inspector UI

---

runner/src/storage.ts

fix: Do not use Iterator.prototype.map due to being unsupported in Safari

---

identity/src/interface.ts
memory/access.ts
memory/clock.ts
memory/deno.json
memory/deno.ts
memory/entity.ts
memory/interface.ts
memory/memory.ts
memory/provider.ts
memory/receipt.ts
memory/settings.ts
memory/test/access-test.ts
memory/test/consumer-test.ts
memory/test/memory-test.ts
memory/test/stress-debug.ts
memory/transaction.ts
toolshed/routes/storage/memory.ts

chore: Use a provided serviceDid in lieu of delegation for memory claims

---

recipes/gmail.tsx

fix refresh auth token

---

runner/src/cell.ts
runner/src/runner.ts
runner/src/schema.ts
runner/src/utils.ts
runner/test/utils.test.ts

- allow aliases to point to paths with aliases in them
- remove unpacking cells that are objects to individual props as aliases in runner
Closes #885

Allow aliases to have aliases in path + Remove extraneous cell unwrapping in runner

---

background-charm-service/src/worker.ts
builder/src/env.ts
builder/src/index.ts
recipes/gmail.tsx
runner/src/env.ts
runner/src/index.ts

Allows requests to call toolshed in Deno environment. Possibly fixes #882?

feat: Exposes a RecipeEnvironment to recipes run in a context.

---

background-charm-service/src/space-manager.ts

chore: Increase rerun interval for BG service from 6s to 60s

---

charm/src/charm.ts
charm/test/charm-references.test.ts
runner/src/cell.ts
runner/src/doc.ts
runner/src/index.ts
runner/src/runner.ts
runner/src/storage.ts
runner/src/utils.ts
runner/test/schema.test.ts

Started PR that we'll need to correctly load charms once we no longer grab all the data by default.
In progress.

Load persistent charms with schema queries

---

jumble/src/components/SpecPreview.tsx

Prevents zero-height issue
Fixes CT-117
Fixes CT-107

Fix race conditions in SpecPreview animation

---

recipes/gcal.tsx

adds the ability to see a table of calendars you can switch to

add option to show calendar list

---

jumble/src/components/NetworkInspector.tsx
jumble/src/components/User.tsx
jumble/src/components/commands.ts
jumble/src/contexts/CharmManagerContext.tsx
jumble/src/main.tsx
jumble/src/routes.ts
jumble/src/views/FullscreenInspectorView.tsx
runner/src/storage/inspector.ts
runner/src/storage/remote.ts

feat: Open inspector in new tab command

---

iframe-sandbox/src/csp.ts

Also need to allowlist `fonts.gstatic.com` for `font-src`, in addition to the CSS

feat: Allow fonts loaded from fonts.gstatic.com

---

background-charm-service/src/env.ts
background-charm-service/src/main.ts
background-charm-service/src/service.ts
background-charm-service/src/space-manager.ts
background-charm-service/src/utils.ts
background-charm-service/src/worker-controller.ts

- include DID in relevant logging statements
- remove timestamp as systemd already pre-pends
- remove over-active logging of status every 100ms (active charm, ...)

better worker logging

---

charm/src/charm.ts
jumble/src/components/commands.ts

https://github.com/user-attachments/assets/dfe69b65-359d-4d25-aae4-9945dc8375d2

Add new 'Duplicate Charm' command

---

background-charm-service/src/space-manager.ts

as resources are exhausted in deployment

chore: Do not recreate worker env on terminal error/loose errors

---

toolshed/routes/ai/llm/generateText.ts
toolshed/routes/ai/llm/llm.handlers.ts
toolshed/routes/ai/llm/models.ts

also supports sending metadata from client (but we aren't setting in jumble yet)

add model/user to phoenix traces

---

charm/src/iterate.ts
llm/src/prompts/charm-describe.ts
llm/src/prompts/charm-suggestions.ts
llm/src/prompts/code-and-schema-gen.ts
llm/src/prompts/json-gen.ts
llm/src/prompts/recipe-fix.ts
llm/src/prompts/spec-and-schema-gen.ts
llm/src/prompts/workflow-classification.ts

This adds the prompt flow name & context to generating/iterating/fixing recipes

Workflow phoenix metadata

---

jumble/src/components/NavPath.tsx

Context https://discord.com/channels/1232452732963655720/1360266614204793047

fix: wrong charm title

---

jumble/src/components/commands.ts

The workflow was being constructed incorrectly, trying a new format where I just stick the JSON directly in the prompt. This might not be ideal but it does work.

Fix Advanced -> JSON import

---

llm/src/prompts/json-import.ts
seeder/jumble.ts

import json should use schema instead of data

---

jumble/src/iframe-ctx.ts

Fixes stale generations lingering in the activity panel by handling non-success response codes.

Wrap iframe LLM call in try-catch

---

charm/src/manager.ts

These schema had a double satisfies JSONSchema

Remove redundant satisfies JSONSchema

---

jumble/src/components/CharmRunner.tsx

Currently, `submitAutomaticErrorFeedback` depends on `charm` argument, which changes when something(?) in the space is updated (e.g. making a new charm in the same space), causing a viewed charm to rerender. As the `charm` param can be `!==` to a previous `charm` object while still representing the same ID, we can't use it as a stable dependency. Instead, rely on `id` and request a charm from the manager (whose instance is stable) when needed.

fix: Do not rerender everytime CharmRunner's charm changes

---

packages/runner/src/builtins/llm.ts

just require at least one message

don't require system message in built-in llm call

---

packages/seeder/processor.ts
packages/seeder/verifier.ts

- url creation
- json recipe creation handles non-object inputs

seeding improvements

---

packages/runner/src/builtins/if-else.ts
recipes/ifelse_test.tsx

Should be a cleaner implementation, leveraging more of the better tested logic around aliases and so on.

IfElse using cell abstractions

---

packages/charm/src/commands.ts
packages/charm/src/manager.ts
packages/html/src/jsx.ts
packages/html/src/render.ts
packages/identity/src/identity.ts
packages/memory/memory.ts
packages/memory/space.ts
packages/runner/src/cell.ts
packages/runner/src/doc.ts
packages/runner/src/storage.ts
packages/runner/src/utils.ts
packages/utils/src/defer.ts
packages/utils/src/encoding.ts
packages/utils/src/sleep.ts
packages/utils/src/types.ts

Minor cleanups:
- Add missing jsdocs
- Reorder imports according to guidelines
- Some type changes
(Done by Claude)

Minor cleanups like JSDocs, reordering imports, etc. by Claude

---

packages/cli/curl.ts
packages/runner/src/storage/cache.ts

Fixed a bug in cache where we were including the since field when calculating the cause.
Added an error message to cache when our queries fail, since they were being silently ignored.

Added support for deleting from the curl command tool

---

packages/background-charm-service/src/schema.ts
packages/background-charm-service/src/utils.ts
packages/background-charm-service/src/worker.ts
packages/charm/src/manager.ts
packages/runner/src/storage.ts

Improve worker interactions with classified charms for CT-409 (#1176)

---

packages/background-charm-service/src/worker-controller.ts

correct worker state message in logTaskResults

---

.claude/commands/setup-space.md
packages/cli/commands/charm.ts
packages/cli/lib/charm.ts

- **Add support for linking to arbitrary cells OR charms**
- Update `setup-script` to explain linking to data
- Confirmed working testing with live instance

`ct charm link` support arbitrary cells as well as charms

---

packages/runner/src/runtime.ts
packages/runner/src/storage/interface.ts
packages/runner/src/storage/transaction-shim.ts
packages/runner/src/uri-utils.ts
packages/runner/test/storage-transaction-shim.test.ts

Just transitional, so we can move the code to use this API while keeping the rest the same. So commit is a no-op, there is no rollback, etc.
It does introduce a few more changes to the interface though.

Implement a shim of the new transaction API using DocImpl
