commontoolsinc/labs

rfcs/2024-05-31-three-authors.md
[rendered](https://github.com/commontoolsinc/labs/blob/rfc/three-software-authors/rfcs/2024-05-31-three-authors.md)
=> rfc: Three Software Authors

typescript/packages/common-frp/README.md, typescript/packages/common-frp/src/dom.ts, typescript/packages/common-frp/src/operators.ts, typescript/packages/common-frp/src/signal.ts, typescript/packages/common-frp/src/stream.ts
- Add 2-argument variant to pipe
- Add stream.subject
- Rename stream.stream to stream.generate
- Rename signal.signal to signal.state (similar to TC39 signals)
=> API improvements

typescript/packages/common-frp/src/operators.ts, typescript/packages/common-frp/src/publisher.ts, typescript/packages/common-frp/src/signal.ts, typescript/packages/common-frp/src/stream.ts
=> Clean up common frp

typescript/packages/common-frp/src/dom.ts, typescript/packages/common-frp/src/operators.ts, typescript/packages/common-frp/src/publisher.ts, typescript/packages/common-frp/src/signal.ts, typescript/packages/common-frp/src/stream.ts
This allows us to provide traversal and serialization methods from subscribers, while returning a limited sink-only view over derived streams.
=> Build FRP stream graph out of subscribers

Cargo.lock, Cargo.toml, rust/usuba-bundle/Cargo.toml, rust/usuba-bundle/src/lib.rs, rust/usuba/Cargo.toml, rust/usuba/src/bake/javascript.rs, rust/usuba/src/bin/usuba.rs, rust/usuba/src/openapi.rs, rust/usuba/src/routes/bundle/javascript.rs, rust/usuba/src/routes/bundle/mod.rs, rust/usuba/src/routes/mod.rs, rust/usuba/src/serve.rs, typescript/common/runtime/package.json, typescript/common/runtime/src/common/data/dictionary.ts, typescript/common/runtime/src/helpers.ts, typescript/common/runtime/src/rpc/index.ts, typescript/common/runtime/src/worker/index.ts, typescript/common/runtime/src/worker/pool.ts, typescript/common/runtime/src/worker/ses/runtime.ts, typescript/packages/runtime-demo/index.html, typescript/packages/runtime-demo/src/demo7.ts, typescript/packages/runtime-demo/src/index.ts, typescript/packages/usuba-api/openapi.json, typescript/packages/usuba-api/package.json, typescript/packages/usuba-api/scripts/update-openapi-spec.sh
This change enables support for external libraries in sandboxed JavaScript modules. In order to depend on an external library, you must import it as a module from a valid URL (web / Deno-style) that is accessible on the network that the build server is running on.
=> feat: Support for external libraries in JS sandbox

typescript/package-lock.json, typescript/packages/common-ui/src/components/button.ts, typescript/packages/common-ui/src/components/datatable.ts, typescript/packages/common-ui/src/components/dict.ts, typescript/packages/common-ui/src/components/div.ts, typescript/packages/common-ui/src/components/h1.ts, typescript/packages/common-ui/src/components/p.ts, typescript/packages/common-ui/src/components/span.ts, typescript/packages/common-ui/src/deep-freeze.ts, typescript/packages/common-ui/src/hyperscript/render.ts, typescript/packages/common-ui/src/hyperscript/view.ts
Allow the user to supply extraneous properties, we will just ignore them.
=> Make `common-ui` component properties lenient

rust/usuba/src/routes/ui.rs, rust/usuba/src/serve.rs
This change drops the original, very basic UI that we built for Usuba and also takes out the reverse-proxying behavior. Instead, we serve the lookslike prototype directly. When building for release, the lookslike prototype UI is bundled into the `usuba` binary.
=> feat: Replace Usuba UI w/ Lookslike Prototype

typescript/packages/lookslike-prototype/src/components/modules/com-module-code.ts, typescript/packages/lookslike-prototype/src/data.ts, typescript/packages/lookslike-prototype/src/eval.ts, typescript/packages/lookslike-prototype/src/graph.ts
Customize SES, WASM or CC on a per block basis
=> Configurable eval mode for code blocks

typescript/package-lock.json, typescript/packages/lookslike-prototype/package.json, typescript/packages/lookslike-prototype/public/wasi-shim, typescript/packages/lookslike-prototype/public/wasi.js
These paths were an implementation detail of `usuba-ui`, but are load bearing when it comes to polyfilling Wasm Components in the runtime. We should fix this, but in the mean time this is the short path to get the lookslike prototype going.
=> fix: Add missing WASI shim to lookslike prototype

typescript/packages/common-ui/src/components/common-button.ts, typescript/packages/common-ui/src/components/common-todo.ts, typescript/packages/common-ui/src/hyperscript/schema-helpers.ts
=> Add todo events

typescript/package-lock.json, typescript/packages/llm-client/package.json, typescript/packages/llm-client/src/dummy-data.ts, typescript/packages/llm-client/src/index.ts
Introduces a small utility function to trivially generate data based off of a description, some input data and a schema it should adhere to. Should be useful for implementing a prototype of search (cc @seefeldb).
```ts
import { generateData, LLMClient } from "@commontools/llm-client";
const client = new LLMClient({
serverUrl: LLM_SERVER_URL,
tools: [],
system: `Generate dummy data as JSON as per the provided spec. Use the input to imagine what an API response would look like for a request.`,
});
const test = await generateData(
client,
"generate 3 user profiles",
{ name: "John Doe" },
{
type: "array",
items: {
type: "object",
properties: {
name: { type: "string" },
email: { type: "string" },
age: { type: "number" },
role: { type: "string" },
birthday: { type: "string" },
favoriteColor: { …
```
=> Implement dummy data utility

typescript/packages/planning-server/package.json, typescript/packages/planning-server/src/index.ts
cache to json on disk instead of in-memory
- cache lives between restarts
- facilitate debugging by viewing the json files
- purge request(s) from cache by deleting file(s)
=> cache llm calls to disk

typescript/packages/lookslike-high-level/src/runner/builtins/if-else.ts
Remove one level of indirection and hence don't "read" the two branches.
Fixes a glitch where the UI wasn't updating, although it also smells like there are more bugs in the UI layer here.
=> Improve ifElse

typescript/packages/lookslike-high-level/src/recipes/annotation.ts, typescript/packages/lookslike-high-level/src/recipes/home.ts, typescript/packages/lookslike-high-level/src/recipes/local-search.ts, typescript/packages/lookslike-high-level/src/recipes/luft-bnb-search.ts, typescript/packages/lookslike-high-level/src/recipes/todo-list-as-task.ts, typescript/packages/lookslike-high-level/src/recipes/todo-list.ts
I'm attempting a different way to organize the code in this PR, inspired by recent discussions.
The original style closely mimics functions-as-components as seen in many modern frameworks, but because we can't use closures yet (until we write a plugin that translates them), there's a bunch of odd boilerplate.
Here I'm instead declaring all the module-y bits, i.e. `lift` and `asHandler` outside of the recipe function and then use the recipe function just to build the graph, which in most cases boils down to just building the UI.
=> Refactoring demo recipes to pull apart modules and graph declaration

typescript/packages/lookslike-high-level/src/builder/README.md, typescript/packages/lookslike-high-level/src/builder/built-in.ts, typescript/packages/lookslike-high-level/src/builder/index.ts, typescript/packages/lookslike-high-level/src/builder/module.ts, typescript/packages/lookslike-high-level/src/recipes/annotation.ts, typescript/packages/lookslike-high-level/src/recipes/local-search.ts, typescript/packages/lookslike-high-level/src/recipes/luft-bnb-search.ts, typescript/packages/lookslike-high-level/src/recipes/playlist.ts, typescript/packages/lookslike-high-level/src/recipes/todo-list.ts, typescript/packages/lookslike-high-level/test/builder/module.test.ts
They just called `lift` and `asHandler` under the hood and using lift(<implementation>)(<parameters>) instead is fine.
=> Deprecated `apply` and (old) `handler`. Renamed `asHandler` to `handler`.

typescript/packages/common-builder/src/built-in.ts
Ensures that all cell methods can be expected to exist.
=> return CellProxy instead of Value

typescript/packages/lookslike-high-level/src/components/window-manager.ts, typescript/packages/lookslike-high-level/src/data.ts, typescript/packages/lookslike-high-level/src/recipes/home.ts
- Now only one window per saga/gem is allowed
- Highlight existing one instead when reopening the same one
(Also added dataGems to window. for debugging)
=> Fix window closing

typescript/packages/collectathon/view.ts, typescript/packages/common-html/src/render.ts, typescript/packages/common-runner/src/cell.ts, typescript/packages/common-runner/src/index.ts, typescript/packages/lookslike-high-level/src/components/iframe-view.ts, typescript/packages/lookslike-high-level/src/components/index.ts, typescript/packages/lookslike-high-level/src/data.ts, typescript/packages/lookslike-high-level/src/recipes/iframeExample.ts
Minimum viable generative UI.
Some issues with reactivity and sharing the state with the iframe context (see comments in code). I'm using a basic `read`/`write` postMessage API.
=> `iframe` view generation

typescript/packages/common-runner/src/scheduler.ts
Right now `handler((e, state) => state.value = e.value)` accidentally creates an infinite loop as the handler returning a value is treated as issuing another event. Disabling this for now until we find a better way to do this.
=> disable follow-on events for now

typescript/packages/lookslike-high-level/src/recipes/counter.ts, typescript/packages/lookslike-high-level/src/recipes/counters.ts
The fix was moving to aliases instead of cell references when launching a charm with cell, fixed in #191
=> counters now work again with unnested values

typescript/packages/common-builder/src/built-in.ts, typescript/packages/common-builder/src/cell-proxy.ts, typescript/packages/common-builder/src/index.ts, typescript/packages/common-builder/src/types.ts, typescript/packages/common-builder/test/recipe.test.ts, typescript/packages/common-runner/src/builtins/fetch-data.ts, typescript/packages/common-runner/src/builtins/if-else.ts, typescript/packages/common-runner/src/builtins/index.ts, typescript/packages/common-runner/src/builtins/llm.ts, typescript/packages/common-runner/src/builtins/map.ts, typescript/packages/common-runner/src/builtins/stream-data.ts, typescript/packages/common-runner/src/index.ts, typescript/packages/common-runner/src/module.ts, typescript/packages/common-runner/src/runner.ts, typescript/packages/common-runner/test/recipes.test.ts
Used primarily for modules that don't follow the regular flow, e.g. because they are async, need raw access to cells, etc.
=> Simplifying interface to build builtin / trusted / raw modules

typescript/packages/common-runner/src/builtins/map.ts, typescript/packages/common-runner/src/cancel.ts, typescript/packages/common-runner/src/index.ts, typescript/packages/common-runner/src/module.ts, typescript/packages/common-runner/src/runner.ts, typescript/packages/common-runner/src/scheduler.ts, typescript/packages/common-runner/test/runner.test.ts, typescript/packages/common-runner/test/scheduler.test.ts
```ts
// Invoke as usual
const result = run(myRecipe, { ... });
// Halt execution
stop(result);
// Restart
// `undefined` means no new bindings
run(myRecipe, undefined, result);
// Replace recipe and/or bindings (WARNING: Needs another PR to be more sensible)
run(myNewRecipe, { new bindings or initial values }, result);
```
TODO: For changing recipes it's currently very dumb in terms of reusing data and will likely fail. Don't use that yet.
=> Stop & restart recipe runs

typescript/packages/common-builder/src/index.ts, typescript/packages/common-builder/src/recipe.ts, typescript/packages/common-builder/src/types.ts, typescript/packages/common-builder/src/utils.ts, typescript/packages/common-builder/test/recipe.test.ts, typescript/packages/common-html/package.json, typescript/packages/common-html/src/view.ts, typescript/packages/common-runner/src/builtins/map.ts, typescript/packages/common-runner/src/cell.ts, typescript/packages/common-runner/src/runner.ts, typescript/packages/common-runner/src/utils.ts, typescript/packages/common-runner/test/recipes.test.ts, typescript/packages/common-runner/test/runner.test.ts
Before inputs and outputs lives in the same namespace.
Now `run` returns the cell representing the results (which is actually a "query" via aliases to the actual cells containing the results).
Cells have now have a `sourceCell` that generate their content, so `.sourceCell` on the cell returned by `run` returns the cell that contains the remaining information, including references to parameters and internal cells.
One advantage is that `.map()` on a cell now works a lot more like one would expect: Only the outputs of the recipe passed to it are in the output.
=> Refactor: Split inputs and outputs in recipes

typescript/packages/common-builder/src/cell-proxy.ts, typescript/packages/common-builder/src/types.ts, typescript/packages/common-runner/src/builtins/map.ts, typescript/packages/common-runner/src/runner.ts, typescript/packages/common-runner/test/html-recipes.test.ts
It's now the same as `lift`, which is good, because they can be used interchangeably (i.e. a caller doesn't know which it is).
This now also allows mapping over arrays of arrays and arrays of literals. Before only mapping over arrays of objects was possible.
=> Feature: Allow parameters to recipe to also be arrays or literals

typescript/packages/common-builder/src/index.ts, typescript/packages/common-builder/src/opaque-ref.ts, typescript/packages/common-runner/src/cell.ts, typescript/packages/common-runner/src/runner.ts, typescript/packages/common-runner/src/utils.ts, typescript/packages/common-runner/test/recipes.test.ts, typescript/packages/common-runner/test/runner.test.ts, typescript/packages/common-runner/test/utils.test.ts
`lift`, like `handler` can return recipes (i.e. queries). The result of the query is then the result of the `lift`. For `lift`, any rerun will override the previous one, for `handler` each is a new charmlet.
=> Run queries returned by lift

typescript/packages/planning-server/src/models.ts
I assume that the import in `index` is triggering before we load the env, causing `model.ts` to evaluate before the env is ready and skipping all the models.
Duplicating this call is silly but it does indicate a lifecycle problem wrt handling environment in the app.
=> Force loading environment variables in `models.ts`

typescript/packages/common-builder/src/opaque-ref.ts, typescript/packages/common-builder/test/recipe.test.ts, typescript/packages/common-runner/src/builtins/map.ts, typescript/packages/common-runner/test/recipes.test.ts
support `list.map((item, index) => ...)`
implementation:
- turn underlying recipe into one that gets `item` and `index` and call passed function with both of those
- remember prior charmlets by index, not by reference, since now they are index dependent
=> add support for `index` to `map`

typescript/packages/common-builder/src/module.ts, typescript/packages/common-builder/src/types.ts, typescript/packages/common-builder/test/module.test.ts, typescript/packages/common-runner/src/runner.ts, typescript/packages/common-runner/test/recipes.test.ts
```tsx
const clickHandler = handler(...);
...
<button onclick={clickHandler({ item }))>
```
is a bit confusing as it looks like it's called when an event happens, but really we're creating an event handler ahead of timing and binding data to it.
This PR adds a `.with` method to handlers, so that we can write
```tsx
<button onclick=`{clickHandler.with({ item })}`>
```
which hopefully is a bit clearer.
This PR also overrides `.bind` to do the same, and then calls the handler with the state parameter bound to `this`. This requires passing an anonymous `function` instead of an arrow function:
```ts
const incHandler = handler<
{ amount: number },
{ counter: { value: number } }
>(function ({ amount }) {
this.counter.value += amount;
});
```
or just
```ts
const incHandler = handler(function …
```
=> add .with support to `handler` output

typescript/packages/toolshed/routes/ai/spell/spell.test.ts, typescript/packages/toolshed/routes/storage/blobby/blobby.handlers.ts, typescript/packages/toolshed/routes/storage/blobby/blobby.routes.ts, typescript/packages/toolshed/routes/storage/blobby/blobby.test.ts
This PR adds a few features to the blobby API
* key-prefix search: so you can fetch blobs that have keys beginning with a string like `spell-`
* full text search (very basic/rudimentary, this will be slow/bad when we have a large number of keys)
* fetch blobs based on list of specific keys
=> Blobby additions

typescript/packages/lookslike-high-level/src/components/window-manager.ts, typescript/packages/lookslike-high-level/src/recipes/articlesIframe.html, typescript/packages/lookslike-high-level/src/recipes/articlesIframe.tsx, typescript/packages/lookslike-high-level/src/recipes/index.ts, typescript/packages/lookslike-high-level/src/recipes/reading-list.tsx, typescript/packages/lookslike-high-level/vite.config.ts, typescript/packages/toolshed/routes/ai/spell/behavior/effects.ts, typescript/packages/toolshed/routes/ai/spell/behavior/strategies/scanBySchema.ts, typescript/packages/toolshed/routes/ai/spell/behavior/strategies/scanForKey.ts, typescript/packages/toolshed/routes/ai/spell/behavior/strategies/scanForText.ts, typescript/packages/toolshed/routes/ai/spell/fulfill.ts, typescript/packages/toolshed/routes/ai/spell/spell.handlers.ts, typescript/packages/toolshed/routes/ai/spell/spell.index.ts, typescript/packages/toolshed/routes/ai/spell/spell.routes.ts
When hitting a `/recipe/:recipeId` URL, use the new toolshed `fulfill` endpoint to request data that will fit the schema.
I will walk through how the fulfill process works on a call, since it's a bit hairy, but it seems to work! I'm unsure how to integrate further beyond my stab in `window-manager.ts` but @anotherjesse hopefully you can follow my lead in terms of usage?
Happy to land this PR but going through the process so you can read the diff first.
https://github.com/user-attachments/assets/6e580ab1-0d56-40cd-9aa1-43828771afd9
=> Fulfill argument schema with spellcaster when launching recipe

typescript/packages/lookslike-high-level/src/components/sidebar.ts, typescript/packages/lookslike-high-level/src/data.ts, typescript/packages/spellbookjr/app/components/recipe-card.tsx, typescript/packages/spellbookjr/app/components/search-box.tsx, typescript/packages/spellbookjr/app/lib/blobby.ts, typescript/packages/spellbookjr/app/page.tsx
This PR makes Spellbook Jr. more useful.
If you want to share a spell for other folks to use, you can now do so by clicking the "Publish to spellbook" button. This prompts you for a title and hashtags. 
Also updated Spellbook Jr. to only display spells that have been manually published with user-defined title and tags
=> Spellbook Jr. Improvements

typescript/packages/common-iframe-sandbox/README.md, typescript/packages/common-iframe-sandbox/src/common-iframe-sandbox.ts, typescript/packages/common-iframe-sandbox/src/ipc.ts, typescript/packages/common-iframe-sandbox/src/outer-frame.ts, typescript/packages/common-iframe-sandbox/test/iframe.test.js
Use nested sandbox frames to provide CSP via meta tags rather than the less-supported iframe csp property.
PROS: appealing that there's a trusted intermediary that does not share a root origin. works consistent across browsers.
CONS: a bit messy nesting frames, performance could be an issue though i'm not concerned here.
The intermediary could be served with CSP HTTP headers in the future as a static asset (on a separate domain even) as an extra layer. Probably comparable to the inline version. could more easily share e.g ipc implementation between host and intermediary
will be a convenient time to uniquely identify frame messages such that we can support more than one common-iframe at a time
```js
// ┌──────────────┐              ┌───────────────┐
// │     Host     │              │ …
```
=> feat: Use nested sandbox frames to provide CSP

typescript/packages/common-memory/interface.ts, typescript/packages/common-memory/lib.ts, typescript/packages/common-memory/package.json
this fixes `pnpm run build` in common-charm/lookslike-high-level/jumble by
only exporting the interfaces from node's package.json
=> only export types in node build

typescript/packages/common-memory/deno.json, typescript/packages/common-memory/deno.ts, typescript/packages/common-memory/error.ts, typescript/packages/common-memory/interface.ts, typescript/packages/common-memory/lib.ts, typescript/packages/common-memory/router.ts, typescript/packages/common-memory/store.ts, typescript/packages/common-memory/test/router-test.ts, typescript/packages/common-memory/test/store-test.ts, typescript/packages/toolshed/routes/storage/memory/memory.handlers.ts, typescript/packages/toolshed/routes/storage/memory/memory.index.ts, typescript/packages/toolshed/routes/storage/memory/memory.routes.ts
Introduces a new capability to list memories or get by `the`.
This PR introduces a GET handler for `/:replica/[:the]`, if `the` is omitted all the memories are listed by querying the `state` view in SQLite.
Includes tests but we may want to adjust the actual behaviour of the implementation around retracted items.
=> (`common-memory`) First pass implementation of `get` and `list` behaviour

typescript/packages/common-memory/deno.json, typescript/packages/common-memory/lib.ts, typescript/packages/toolshed/routes/storage/memory/memory.handlers.ts
This pull request teases apart some of the inter-mingling of concerns in `toolshed` and `common-memory`, to fix a bug found in sentry https://github.com/commontoolsinc/labs/issues/316
When exposed in `toolshed`, the `common-memory` code runs into issues with duplicate request body / json parsing.
To fix this bug, and to not run the entire http processing stack twice, I think we should move all of the http handling concerns for the `/api/storage/memory` endpoint up into the `toolshed` hono app; and update `common-memory` to expose non-http-handling functions for `query`, and `patch`.
Some background on the bug: The `toolshed` hono api has openapi request schema validation. The first thing that happens to a request is that it is parsed and validated. This happens to read the request body …
=> Toolshed common-memory cleanup

typescript/packages/common-iframe-sandbox/src/csp.ts, typescript/packages/common-iframe-sandbox/src/outer-frame.ts, typescript/packages/common-iframe-sandbox/test/iframe-csp.test.js
Explicitly define the top-level origin for CSP, as 'self' is interpreted differently in browsers in nested, sandboxed iframes. In Firefox, "self" doesn't appear to select any origins in a sandboxed iframe (null origin).
=> chore: Explicitly define the top-level origin for CSP

typescript/packages/jumble/src/components/NavPath.tsx
Small change, but mostly want to double check that this is allowed in React, i.e. that setCharmName can be called at any time.
=> Update charm name in UI when it changes in charm

typescript/packages/jumble/src/contexts/CharmManagerContext.tsx
I'm running out of steam, but was hoping to get this fixed before I left for the day. After working through this with o3-mini, I think this might be a reasonable fix.
In the breaking commit, the removal of the `useEffect` (and the associated state/references) in `CharmManagerContext.tsx` meant that a new instance of the `CharmManager` was being created on every render rather than only when the `effectiveReplica` changed.
By wrapping the creation of the `CharmManager` in a `useMemo` that depends on `effectiveReplica`, the code ensures that the same instance is used across renders unless the effective replica actually changes.
=> Potential fix for issue #380

typescript/packages/jumble/src/components/CommandCenter.tsx, typescript/packages/jumble/src/components/TranscribeCommand.tsx, typescript/packages/jumble/src/components/commands.ts, typescript/packages/jumble/src/contexts/BackgroundTaskContext.tsx, typescript/packages/jumble/src/main.tsx, typescript/packages/jumble/src/utils/indexing.ts, typescript/packages/jumble/src/utils/llm.ts, typescript/packages/jumble/src/views/CharmDetailView.tsx, typescript/packages/jumble/src/views/Shell.tsx
- https://github.com/commontoolsinc/labs/issues/389
- rework command abstraction to handle dynamic menu items more elegantly
- implement background job abstraction (`useBackgroundJobs` hook)
- this may come in handy for variants, or anywhere you want to run a task that persists while navigating around the app
- implement counter job example
- implement basic charm indexer
- for each charm, describe it via LLM and save to `common-memory` under `text/plain;variant=description`
https://github.com/user-attachments/assets/8f096814-2a88-444c-a2d6-f1e4758c4bc4
=> Background Jobs + Basic Charm Indexer

typescript/packages/common-builder/src/types.ts, typescript/packages/common-html/src/render.ts, typescript/packages/common-runner/src/builtins/map.ts, typescript/packages/common-runner/src/cell.ts, typescript/packages/common-runner/src/scheduler.ts, typescript/packages/common-runner/src/schema.ts, typescript/packages/common-runner/src/utils.ts, typescript/packages/common-runner/test/cell.test.ts, typescript/packages/common-runner/test/scheduler.test.ts, typescript/packages/common-runner/test/schema.test.ts
Turns out that the renderer use-case is a neat power-user use-case of the schema stuff, so this PR has a bunch of fixes and new features.
Renderer is now also using the regular runner scheduler (before it was all a separate system!).
=> Renderer using new `Cell` with VDOM as schema

.github/workflows/ui-tests.yml, typescript/packages/common-html/package.json, typescript/packages/common-identity/README.md, typescript/packages/common-identity/package.json, typescript/packages/common-identity/src/derived-key.ts, typescript/packages/common-identity/src/ed25519/index.ts, typescript/packages/common-identity/src/ed25519/native.ts, typescript/packages/common-identity/src/ed25519/noble.ts, typescript/packages/common-identity/src/ed25519/utils.ts, typescript/packages/common-identity/src/key-store.ts, typescript/packages/common-identity/src/keys.ts, typescript/packages/common-identity/src/root-key.ts, typescript/packages/common-identity/src/space-key.ts, typescript/packages/common-identity/src/utils.ts, typescript/packages/common-identity/test/ed25519.test.js, typescript/packages/common-identity/test/utils.js, typescript/packages/common-identity/web-test-runner.config.js, typescript/packages/common-iframe-sandbox/package.json, typescript/packages/common-ui/package.json, typescript/packages/pnpm-lock.yaml
chore: Add tests and fallback for client-side ed25519 implementation.
* Introduce DerivedKey, SpaceKey
* Introduce Ed25519KeyPair, wrapping native and client (@noble/ed25519)
implementations.
* Add unit tests. Enable ed25519 flags in Chromium while running.
* Update @web/test-runner everywhere to 0.20.0.
=>  chore: Add tests and fallback for client-side ed25519 implementation

typescript/packages/common-html/src/jsx.ts, typescript/packages/common-html/src/render.ts, typescript/packages/common-runner/src/cancel.ts, typescript/packages/common-runner/src/cell-map.ts, typescript/packages/common-runner/src/cell.ts, typescript/packages/common-runner/src/doc.ts, typescript/packages/common-runner/src/index.ts, typescript/packages/common-runner/src/reactivity.ts, typescript/packages/common-runner/src/scheduler.ts, typescript/packages/common-runner/src/schema.ts, typescript/packages/common-runner/src/utils.ts, typescript/packages/common-runner/test/cell.test.ts, typescript/packages/common-runner/test/schema.test.ts, typescript/packages/jumble/src/utils/charms.ts, typescript/packages/jumble/src/views/CharmList.tsx
Added proper DOM diffing and removed a lot of now redundant reactivity stuff by moving everything to assume `Cell`.
Other changes:
- Cell.sink callbacks can return cancel functions that are called before the next call and at the end
- Added a `Stream` type
- Changed specifics of how `asCell` behaves when encountering aliases, etc. 
- Fixed scheduling bug when listening to changes on arrays
- Removed a lot of redundant calling
- A lot more tests, especially around asCell, scheduling, etc.
Quick follow-up: Renaming and moving between files. Just wanted to keep the diffs clean.
=> Common-html/render: Cleanup, DOM diffing & lots of helpers & fixes discovered while doing so

typescript/packages/common-identity/examples/index.html, typescript/packages/common-identity/package.json, typescript/packages/common-identity/src/ed25519/index.ts, typescript/packages/common-identity/src/ed25519/native.ts, typescript/packages/common-identity/src/ed25519/noble.ts, typescript/packages/common-identity/src/ed25519/utils.ts, typescript/packages/common-identity/src/identity.ts, typescript/packages/common-identity/src/interface.ts, typescript/packages/common-identity/src/pass-key.ts, typescript/packages/common-identity/src/utils.ts, typescript/packages/common-identity/test/ed25519.test.js, typescript/packages/pnpm-lock.yaml
* Add fromDid/Did methods for verifiers.
* Remove redundant hashing in derivation
* Use SHA-256 when deriving keys.
=> feat: Split up Identity into Signer and Verifier components.

typescript/packages/common-html/src/render.ts
Uncaught Error: Unsupported static child type
at renderChild (render.ts:132:20)
at updateChildren (render.ts:157:29)
at render.ts:187:63
at subscribeToReferencedDocs (cell.ts:258:41)
at Object.sink (cell.ts:195:7)
at effect (reactivity.ts:21:18)
at bindChildren (render.ts:187:29)
at renderNode (render.ts:75:26)
at render.ts:97:47
at subscribeToReferencedDocs (cell.ts:258:41)
=> Fix rendering exception when cell has value 'undefined'

typescript/packages/common-charm/src/syncRecipe.ts, typescript/packages/jumble/src/components/CommandCenter.tsx, typescript/packages/jumble/src/components/commands.ts, typescript/packages/jumble/src/search.ts, typescript/packages/jumble/vite.config.ts, typescript/packages/toolshed/routes/ai/spell/behavior/effects.ts, typescript/packages/toolshed/routes/ai/spell/behavior/spell-search.ts, typescript/packages/toolshed/routes/ai/spell/spell.handlers.ts, typescript/packages/toolshed/routes/ai/spell/spell.index.ts, typescript/packages/toolshed/routes/ai/spell/spell.routes.ts, typescript/packages/toolshed/routes/storage/memory/memory.routes.ts
- **Replica must start with `did` when contacting common-memory**
- **Fix spell search path in production**
- **Mock up new commands and fix open/close bugs**
- **WIP new toolshed routes**
- **Fix malformed query**
- **Fix memory retrieval**
- **Remove hardcoded BLOBBY_URL**
- **Implement 'reuse' endpoint**
- **Hacking my way working data reuse between spells**
- **It's alive!**
=> Spellcaster: Reuse data with another spell

typescript/packages/jumble/README.md, typescript/packages/jumble/package.json, typescript/packages/jumble/src/components/ShellHeader.tsx, typescript/packages/jumble/src/components/User.tsx, typescript/packages/jumble/src/contexts/AuthenticationContext.tsx, typescript/packages/jumble/src/main.tsx, typescript/packages/jumble/src/views/AuthenticationView.tsx, typescript/packages/jumble/src/views/Shell.tsx, typescript/packages/pnpm-lock.yaml
* Introduce `AuthenticationContext` for interacting with the authenticated user
* Main entry now kicks off to `AuthenticationView` if not authenticated.
* After registering, we need to also "login". Clicking "login" after registering should go through the WebAuthn flow, and the derived keys are then stored.
* If authenticated, a `User` widget is rendered in the `ShellHeader`, color derived from the authenticated key. Clicking this button clears authentication storage for re-testing.
* Add running instructions to README
=> feat: Integrate common-identity in Jumble.

typescript/packages/common-identity/src/ed25519/index.ts, typescript/packages/common-identity/src/ed25519/native.ts, typescript/packages/common-identity/src/ed25519/noble.ts, typescript/packages/common-identity/src/identity.ts, typescript/packages/common-identity/src/interface.ts, typescript/packages/common-identity/src/key-store.ts, typescript/packages/common-identity/test/ed25519.test.js, typescript/packages/common-identity/test/identity.test.js, typescript/packages/jumble/src/components/User.tsx
Move the asynchronous requirements (native ed25519 requires exporting a public key) inside generation, caching the DID, so that the external interfaces are synchronous; for transaction work
=> chore: Update the did() method in common-identity to be synchronous

typescript/packages/common-runner/src/cell.ts, typescript/packages/common-runner/test/call-map.test.ts
Introduces:
- `getCellFromEntityId(entityid, [path, [schema, log]]])` – create a cell from a known entityid, will create underlying doc if necessary
- `getCellFromDocLink(doclink, [schema, [log]])` - where doclink is `cell.getAsDocLink()`, which can be serialized
- `getImmutableCell(data, [schema, [log]])` - creates immutable in-memory data, `log` will be transferred to mutable `Cell` instances linked off of this.
=> Cell creation helpers

typescript/packages/common-charm/src/charm.ts, typescript/packages/common-runner/src/cell.ts
`CharmManager.get(charmId | charm, runIt = true)` now uses the spell's schema in the cell, but always adds `[NAME]` and `[UI]` if present in the charm. You can now pass a charm to it, and it'll return it with the right schema. A new second argument allows turning off automatically launching it.
New: `CharmManager.getArgument(charm)` returns the argument as a cell with the original argument schema.
Note that `CharmManager.getCharms` returns an array of charms, but those only have `[NAME]` and `[UI]` set, since they work off a bare bones schema for charms on that array. So if you then want the the result data or run it call `CharmManager.get(charm)` with it. We should probably just move that into the cell interface itself, i.e. the ability to run it and to represent itself as the schema …
=> CharmManager adds Spell's schemas to .get() with optional running + add .getArgument(charm)

typescript/packages/jumble/src/components/ActionBar.tsx, typescript/packages/jumble/src/components/CharmRunner.tsx, typescript/packages/jumble/src/components/Publish.tsx, typescript/packages/jumble/src/components/ShellHeader.tsx, typescript/packages/jumble/src/components/User.tsx, typescript/packages/jumble/src/contexts/ActionManagerContext.tsx, typescript/packages/jumble/src/main.tsx, typescript/packages/jumble/src/views/CharmDetailView.tsx, typescript/packages/jumble/src/views/Shell.tsx
- **Ripped apart CharmDetailView and split into components**
- **Cleaned up mobile iteration experience**
- **Move edit button to action stack**
- **Move actions out of toolbar and into global abstraction**
https://github.com/user-attachments/assets/a1185644-a3ad-4759-ac36-f7f290fe46bf
=> Mobile compatibility pass

typescript/packages/common-runner/src/runner.ts
otherwise as they are frozen/readOnly, it breaks sync
=> set input event cells to be ephemeral

typescript/packages/jumble/eslint.config.js, typescript/packages/jumble/package.json, typescript/packages/jumble/src/views/CharmList.tsx, typescript/packages/pnpm-lock.yaml
- include `eslint-plugin-import`
- enable `import/extensions` rule for all non-package imports
=> Require file extensions on non-package imports

typescript/packages/common-cli/main.ts, typescript/packages/common-cli/recipes/simpleValue.tsx
updated main.ts and made it a little more generic. parameters:
--space <space name> (default is "common-cli")
--cause <some stable id>
--recipeFile ./path/To/recipe.tsx
--charmId <id to render>
by default renders charm list in recipe, optionally runs recipe and watches specified charm
=> common-cli: generic main.ts + example recipe

typescript/packages/toolshed/routes/ai/spell/handlers/fulfill.ts, typescript/packages/toolshed/routes/ai/spell/handlers/imagine.ts, typescript/packages/toolshed/routes/ai/spell/handlers/recast.ts, typescript/packages/toolshed/routes/ai/spell/handlers/reuse.ts, typescript/packages/toolshed/routes/ai/spell/json.ts, typescript/packages/toolshed/routes/ai/spell/spell.handlers.ts, typescript/packages/toolshed/routes/ai/spell/spell.index.ts, typescript/packages/toolshed/routes/ai/spell/spell.routes.ts
- NEW: fast version of `fulfill`, `imagine`
- clean up code structure and flag methods as obselete
=> Refactor spellcaster routes

typescript/packages/common-charm/src/charm.ts, typescript/packages/jumble/src/components/commands.ts
Ben: PTAL if this feels right. I added a new `getArgument` helper to CharmManager to abstract the sourceCell stuff away (cc: Jake for that). The other call path comes via spellcaster, see the TODO (not urgent, just wanting to verify that my interpretation is correct).
=> remove direct use of sourceCell from jumble

typescript/packages/common-html/src/render.ts
Since our linter now enforces `onClick` instead of `onclick`, but since that's React standard it might anyway be how code is going to be generated.
Mostly this means that all our custom events have to be lowercase as well, which for now they all are.
=> fix: render now maps to lowercase DOM events

typescript/packages/common-charm/src/charm.ts
minor improvement to improve debugging.
=> fix: don't throw when manager.get() doesn't return a charm

.github/workflows/lint.yml, typescript/packages/common-cli/arena.ts, typescript/packages/common-cli/gmail.tsx, typescript/packages/common-html/test/html-recipes.test.tsx, typescript/packages/common-memory/consumer.ts, typescript/packages/common-memory/entity.ts, typescript/packages/common-memory/interface.ts, typescript/packages/common-memory/receipt.ts, typescript/packages/common-memory/test/space-test.ts, typescript/packages/common-memory/test/stress-debug.ts, typescript/packages/common-ui/src/components/common-google-oauth.ts
Big changes here are replacing `{}` with `NonNullable<unknown>` -- open to any alternatives
=> chore: Fix remaining lints, add to CI

typescript/packages/toolshed/lib/types.ts, typescript/packages/toolshed/routes/storage/blobby/blobby.handlers.ts, typescript/packages/toolshed/routes/storage/blobby/blobby.index.ts, typescript/packages/toolshed/routes/storage/blobby/blobby.test.ts, typescript/packages/toolshed/routes/storage/blobby/lib/storage.ts, typescript/packages/toolshed/routes/storage/blobby/utils.ts
previously each request to blobby would create/destroy the redis client - let's just keep it running
=> use single redis instead of create/destroy

typescript/packages/common-charm/src/charm.ts, typescript/packages/common-cli/main.ts, typescript/packages/common-cli/recipes/simpleValue.tsx, typescript/packages/deno.lock, typescript/packages/jumble/integration/smoke-test.ts, typescript/packages/jumble/integration/utils.ts, typescript/packages/jumble/src/components/CharmRunner.tsx, typescript/packages/jumble/src/components/NavPath.tsx
this builds upon https://github.com/commontoolsinc/labs/pull/516 - adding more testing
=> integration: create charm using ci, view in jumble

typescript/packages/common-memory/README.md, typescript/packages/common-memory/deno.json, typescript/packages/common-memory/migrate.ts, typescript/packages/common-memory/migrations/000-setup-migrations.sql, typescript/packages/common-memory/migrations/001-drop-maybe_datum.sql, typescript/packages/common-memory/space.ts
Changes here remove complicated joins per @seefeldb findings that creates huge perf wins and same stuff loads goes from 13sec to 675ms on my machine.
I also added a migration scripts that can be used to migrate old db to new one by running it like
```sh
deno task migrate ./path/to/db.sqlite
```
=> fix: remove maybe_datum view

typescript/packages/jumble/src/contexts/CharmManagerContext.tsx, typescript/packages/jumble/src/main.tsx
simplifies the charmmanagercontext as there should always be one
=> redirect to last known replica

typescript/packages/common-memory/migrate.ts, typescript/packages/common-memory/migrations/002-remove_coalesce.sql, typescript/packages/common-memory/space.ts
Changes here migrate data in tables and update memory space implementation so we could remove use of coalesce function in `state` view. On my device it offers slight performance improvement but not a significant one, although difference is so small that I'm not sure if my machine simply has less load this time around.
In addition I have also added bunch of comments to the database schema to document parts that were not obvious, thanks @ellyxir for raising it & I do hope new comments address them.
=> feat: update schema removing need for coalesce

typescript/packages/common-runner/src/doc-map.ts, typescript/packages/common-runner/src/storage.ts, typescript/packages/common-runner/test/storage.test.ts
fixes bug where the same entity in two spaces collided
=> remove duplicated id-to-doc map and remember what is watched instead.

typescript/packages/common-runner/src/cell.ts, typescript/packages/jumble/src/iframe-ctx.ts
This will prevent "normalizing" arrays into a lot of small documents
=> feat: Add Cell.setRaw() to cell & use it in iframe

typescript/packages/jumble/integration/basic-flow.test.ts, typescript/packages/jumble/integration/utils.ts, typescript/packages/jumble/src/views/AuthenticationView.tsx
- **Add aria-labels to AuthenticationView**
- **Select using aria-label for auth utilities**
- **Added a feature to screenshot + snapshot HTML on every assertion, disabled by default**
=> Use aria-label to guide integration tests

typescript/packages/jumble/src/iframe-ctx.ts
throttle writes from iframe to avoid cpu spinning and locking up
=> after 20 writes per second, only write the last value every 0.1s

typescript/packages/common-runner/src/cell.ts
* getCell(space, cause, schema?, log?) to create cells from cause
* fixed type for .key to not return `never`
=> feat: getCell(space, cause, schema?, log?) to create cells from cause

jumble/src/components/commands.ts, runner/src/cell.ts
@bfollington i was curious why there are two placeholders
=> Feat: Show examples from schema in charm action placeholder

jumble/src/iframe-ctx.ts
Streams don't have a get() method, so we need to use optional chaining to avoid errors when a stream is used in a charm input.
=> fix: handle streams in charm input by using optional chaining for get()

builder/src/index.ts, builder/src/recipe.ts, builder/src/types.ts, jumble/vite.config.ts, recipes/gcal.tsx, recipes/gmail.tsx, runner/src/builtins/fetch-data.ts, runner/src/builtins/stream-data.ts, runner/src/cell.ts, runner/src/query-result-proxy.ts, runner/src/runner.ts, runner/src/scheduler.ts, runner/src/utils.ts, runner/test/cell.test.ts, runner/test/scheduler.test.ts, runner/test/utils.test.ts
Removed `normalizeToDocLinks` which was nasty
- No longer turning arrays into docs by default
- When passing `[ID]` (a symbol) on an object, it will convert those into cells using the passed ID as part of the cause. The rest of the cause comes from the running frame, i.e. the charm if it's a derived function or the event if it's a handler
- Cell.push() will still create individual cells per item
- Diffing changes more granularly
Also
- updated Gmail recipe accordingly to use cells and deliberate IDs
- add a new INTEGRATIONS_URL in vite config
Co-authored with @ellyxir and @ubik2
=> Refactor normalize arrays

cli/deno.json, cli/name2did.ts
To run this, if you are in `./labs/cli`, you can run `deno task name2did foo`
```
deno task name2did foo
NAME: foo
SPACE: did:key:z6MkrvSneCFqY1Fv6yBXtrZSRX7XcasyoTttPffFzRzaRnRv
```
If you need to modify the passphrase used to derive the space did, you can override it like so:
```
OPERATOR_PASS='yoyoyo' deno task name2did foo
NAME: foo
SPACE: did:key:z6Mkg7fKkueYuduXcV5DNUiUyg812syaDYE2zkv4eo7qpJn
```
=> adding a little cli to quickly convert space names to dids

identity/src/ed25519/index.ts, identity/src/ed25519/native.ts, identity/src/ed25519/noble.ts, identity/src/identity.ts, identity/src/interface.ts
to reduce opportunities in appearing in e.g. console.logs
=> chore: set all Identity internals from TS private to JS private

runner/src/cell.ts, runner/src/utils.ts, runner/test/cell.test.ts, runner/test/utils.test.ts
* IDs derived within an array are keyed to the array, not the element
* Aliases overwrite previous aliases
=> Fix: IDs now belong to containing arrays + new aliases override previous ones

charm/src/iframe/static.ts
- **Do not show loading overlay if there are no libraries to load**
=> Fix: skip loader if no libraries

cli/write-to-authcell.ts, runner/src/cell.ts, runner/src/index.ts, toolshed/routes/integrations/google-oauth/google-oauth.utils.ts
Now that cell links have spaces, let's simplify the interface for getCellFromLink
@anotherjesse please double check the auth code, specifically that .space should be there because it's generated by Cell.getAsCellLink(). i'm not 100% that's for sure the case (vs hand creating it as `{ cell: ..., path: ... }`).
=> Simplify interface for getCellFromLink

runner/src/storage.ts, runner/src/storage/volatile.ts, runner/test/storage.test.ts
rename to simplify 'common memory/remote' vs 'in-memory/memory'
=> inmemory -> volatile storage provider

builder/src/recipe.ts, builder/src/utils.ts, builder/test/utils.test.ts, charm/src/iterate.ts
`createJsonSchema` is now descend into Cells/Docs/etc. while using Cell schemas if present.
Whether to copy the example into the defaults is now a boolean.
=> createJsonSchema is now descend into Cells and reuse schemas

charm/src/iframe/static.ts, iframe-sandbox/src/common-iframe-sandbox.ts, iframe-sandbox/src/context.ts, iframe-sandbox/src/ipc.ts, jumble/src/iframe-ctx.ts
Since it's a breaking change in the behavior, I revved the iframe protocol: subscribe now accepts an array of keys, and this triggers the new behavior. In a few weeks, let's remove support for single strings and remove support for the old behavior.
=> don't send data back to the iframe that came from the iframe + change useDoc to not expect that

cli/cast-recipe.ts, cli/deno.json, cli/google-importer.ts, recipes/gmailIntegrationsManagement.tsx, toolshed/routes/integrations/google-oauth/google-oauth.handlers.ts, toolshed/routes/integrations/google-oauth/google-oauth.routes.ts, ui/src/components/common-google-oauth.ts, utils/src/gmail-integration-charms.ts, utils/src/index.ts
This PR has a lot of moving pieces, but the goal was to enable us to keep some state (ie list of email integration spaces and charm ids), and use the managed state to power our background `google-importer.ts` script.
=> Setting up google oauth integration toolshed-system cell

builder/src/opaque-ref.ts, builder/src/recipe.ts, builder/src/types.ts, builder/src/utils.ts, builder/test/opaque-ref-schema.test.ts, charm/src/charm.ts, html/test/html-recipes.test.ts, jumble/src/iframe-ctx.ts, runner/src/cell.ts, runner/src/index.ts, runner/src/schema.ts, runner/src/utils.ts, runner/test/schema-lineage.test.ts, runner/test/utils.test.ts
It turns out the argument schema wasn't actually piped through all the way from recipe creation to running the charm to then what the renderer would pass to e.g. the iframe lit element. This fixes that.
The main steps are:
- builder:
- opaque refs are now schema aware (which is actually also another step towards eventual unification with Cell)
- recipe creation passes argument schema as schema to an opaque ref
- when recipe is being serialized, which currently means opaque refs get turned into aliases, the schemas are written into alias
- runner:
- when following aliases, pick up the schema of the first alias the sets one
- when there is no schema, or a parent schema runs out of specificity (e.g. a prop in vdom that can by any type), then such an alias provided schema is used instead
=> Builder & Runner: Associate argument schema all the way through to cell that goes to renderer

runner/src/runner.ts, runner/test/runner.test.ts
don't overwrite result on recipe restart.
partially fixes #690: renaming charms that don't compute their names will now work
+ tests, also for how defaults are handled.
=> Fix charm renaming

charm/src/iframe/static.ts, charm/src/index.ts, jumble/src/views/CharmDetailView.tsx
- **Store, retrieve and display the current template "version" in the code panel**
Introduces `<meta name="template-version" content="1.0.0">` tag in template, which can be grabbed from the parent context using the new `extractVersionTag` function.
This is displayed in the UI:
=> Store, retrieve and display the current template "version" in the code panel

deno.lock, runner/src/scheduler.ts, runner/test/recipes.test.ts
- changed default behavior to just console.error errors, but not re-throw
- catch errors in handlers
- make sure to resolve promise even if onerror() handlers throw again
- added tests
Fixes #775
=> properly catch errors in handlers and lifted functions

jumble/src/main.tsx, runner/src/index.ts
In Jumble, window.alert() on first caught error coming from a recipe. This is so we don't ignore those. Once they are being generated automatically, we'll want to use a different path.
Note: Default behavior of the scheduler is already to `console.error` any error.
Follow up to #775
=> window.alert() on first error in a recipe

charm/src/iframe/static.ts, iframe-sandbox/src/common-iframe-sandbox.ts, iframe-sandbox/src/health-check.ts, iframe-sandbox/src/ipc.ts, iframe-sandbox/src/outer-frame.ts
Properly handling this is probably best handled by using a bespoke origin served by the backend to isolate each charm, with most browsers running them in their own thread. That is not the case with `srcdoc` iframes AFAICT
=> feat: Implement a health check timer to disconnect charm if inner frame does not respond within timeframe

iframe-sandbox/src/common-iframe-sandbox.ts
In the future, consider other options in #739
=> chore: increase charm crash timeout from 100ms to 3s

iframe-sandbox/src/common-iframe-sandbox.ts, iframe-sandbox/src/ipc.ts, iframe-sandbox/src/outer-frame.ts
Further investigation into iframe process separation:
* Chrome/Safari put null origin frames into their own process (heuristically; this may not always be true e.g. on a resource-constrained/mobile device)
* Firefox does not
* Using a separate origin for the outer frame *does* force process separation on browsers (including Firefox)
* Testing by clicking the color-changing title bar while churning in a frame
Current plan:
* Move terminating frames back to the main thread (from the outer frame) so that if a frame is hanging on e.g. 10s of processing, the main thread can terminate it explicitly while still being blocked e.g. after 2-3s.
* If frames are not separate (Firefox), the main thread must wait a moment for frame churn to stop before terminating (e.g. after 10s of processing, well …
=> feat: Terminate frames from the main thread after failing health check

runner/src/cell.ts, runner/src/doc.ts, runner/src/storage.ts, runner/src/storage/base.ts, runner/src/storage/volatile.ts, runner/test/push-conflict.test.ts
This is a minimal-changes-to-the-code version of adding retry for Cell.push, which is what we use to add charms to the charms list. It's breaking layers of abstractions, so this is rather temporary until we've refactored storage to a point where transactions are a unified concept from scheduler to remote storage provider.
Tests implemented by faking a conflict in volatile storage provider.
Also simplified the logic for waiting for a batch to finish.
=> Add retry on conflict for Cell.push

jumble/src/components/CharmTable.tsx, jumble/src/components/HoverPreview.tsx, jumble/src/views/CharmList.tsx
Fixes #842
https://github.com/user-attachments/assets/a72c7ec5-9078-437d-aac4-2a374e888b22
Fixed an issue where the charm preview in hover tooltips wasn't properly filling the height of its container card, resulting in inconsistent rendering compared to the full CharmView context.
1. Restructured the HoverPreview component with proper flex layout:
- Added explicit height (320px) to the container
- Updated containers to use flex column layout
- Applied flex-grow to the charm content area
- Added overflow handling for content
- Removed hover preview from CharmTable (now handled by CharmLink)
2. Added smooth animation for preview appearance:
- Implemented CSS keyframes for fade-in and scale effects
- Added key-based rerendering when charm changes
3. Fixed related component in CharmList to …
=> Fix #842: CharmPreview in hover tooltip does not fill height of containing card

jumble/src/main.tsx, runner/src/scheduler.ts, runner/test/recipes.test.ts, runner/test/storage.test.ts
It's quite hacky as it depends on all the unsafe_* context, but we can redo that once we have proper contexts there.
Closes #853
=> Add charmId & recipeId in handler and lift errors

identity/src/ed25519/index.ts, identity/src/ed25519/native.ts, identity/src/ed25519/utils.ts, identity/src/identity.ts, identity/src/key-store.ts, identity/test/identity.test.ts
Introduce new methods for generating PKCS8 format keys as direct access to private key material is disallowed, in service of #783
=> feat: Add generatePkcs8, fromPkcs8 static methods on Identity

toolshed/env.ts, toolshed/lib/llm.ts, toolshed/routes/ai/spell/behavior/effects.ts, toolshed/routes/hc_example/index.ts, toolshed/routes/spellbook/spellbook.handlers.ts
This recently broke with a deployment change, we no longer have localhost:8000 in production, so we need a new way to define the api url for internal request routing.
=> Fixing honoclient usage

jumble/src/iframe-ctx.ts
The iframe might send `null` or `undefined` before getting data, which might explain #845.
We'll now catch this by doing a coarse schema check on writes, basically just making sure that `null` can't overwrite an object, etc.
If there is a schema, the schema is used to derive the desired type. Otherwise the current value in the charm sets the type, unless it's undefined, then anything is allowed.
=> coarse schema check on write from iframe

deno.jsonc, deno.lock, recipes/gmail.tsx, runner/src/local-build.ts
Generates markdown from the html context, falling back to plain text
Should help with #866 
Open:
=> Add markdown conversion to gmail recipe

iframe-sandbox/src/outer-frame.ts
This enables [`confirm()` and friends](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#allow-modals), used in some recipes.
Fixes #893
=> feat: Add 'allow-modals' to inner iframe sandbox

cli/memory_demo.ts, jumble/src/components/NetworkInspector.tsx, runner/src/storage.ts, runner/src/storage/remote.ts
Adds unique `id` to a storage that is then used to publish / subscribe updates to inspector / status UI.
=> fix: bind storage inspector to a tab

background-charm-service/cast-admin.ts, background-charm-service/src/env.ts, background-charm-service/src/main.ts, background-charm-service/src/service.ts, background-charm-service/src/space-manager.ts, background-charm-service/src/utils.ts, background-charm-service/src/worker-controller.ts, background-charm-service/src/worker.ts, cli/cast-recipe.ts, cli/main.ts, identity/src/index.ts, identity/src/session.ts
* Configure `openSession` and `createSession` to take `Identity`, not a passphrase, and rename current methods to `[open|create]SessionFromPassphrase`. The passphrase methods should eventually be removed.
* Keys are being serialized (in Deno, Identity should be using native WebCrypto keys, which should be serializable, and not directly expose key material to JS), need to test this works. Once delegation functional, we'll probably want different keys for each Worker.
* Commenting out currently unused env vars
* Rename `WorkerController.prototype.call` to `exec`, wanting to avoid confusion with `Function.prototype.call`
* Should be safe to land before integrating a real key file #890 
Using an identity file is additive, this will fallback to continue using passphrase.
In service of #882 …
=> chore: Thread identity (passphrase or file) and toolshed URL into individual BG workers

runner/src/cell.ts, runner/test/push-conflict.test.ts
Instead of modifying the doc, just do the bare minimum re-applying of the push & return that value
=> Fix retry on push with objects

recipes/gmail.tsx
by returning a promise the charm system can await its completion.
this allows catching exceptions as well as stopping multiple updates happening at the same time
=> gmail updater handler should return promise for proper flow control

recipes/gcal.tsx, recipes/gmail.tsx
- using 'set' causes the information to disappear because it unsets user, which means the schema won't match.  update solves that
- also we were sending the wrong json into set
=> use update vs set & grab the right json

charm/src/charm.ts, charm/test/charm-references.test.ts, jumble/src/views/CharmDetailView.tsx, runner/src/index.ts
=> Show full-depth reference in CharmDetails panel

background-charm-service/src/service.ts, background-charm-service/src/worker-controller.ts
Also log the error; previous usage has arg 2 and 3 flipped, due to `ErrorEvent.prototype.error` satisfying `log`'s `option` type.
In service of #934
=> feat: Handle unhandled errors in worker thread by not crashing parent thread

runner/src/storage.ts
See #924 for why this is useful
=> console.error any errors from storage, including conflict

builder/src/types.ts, runner/src/cell.ts, runner/test/cell.test.ts
Allow inputs to writing cell methods to have a different Cell<> structure than the destination cell
=> Type checking for Cell: Allow setters with different Cell<> structure

background-charm-service/cast-admin.ts, background-charm-service/src/service.ts, background-charm-service/src/space-manager.ts, recipes/bgAdmin.tsx, toolshed/routes/integrations/google-oauth/google-oauth.handlers.ts, utils/src/updaters.ts
- re-auth should re-enable bg flow
- ensure the schemas match & cleanup (status was missing)
- set status on enable/disable/worker error
=> schema fixes / status messages on failures

jumble/src/views/CharmList.tsx
- Fix issue where the empty state is shown when all charms are in trash, preventing users from accessing the trash
- Only show empty state when both main list AND trash are empty
1. Move all charms to trash
2. Verify that the UI still renders and trash section is accessible
3. Empty the trash
4. Verify that empty state is now shown
Fixes #906
Fixes CT-109
=> fix: Show trash section when all charms are in trash

identity/src/ed25519/index.ts, identity/src/ed25519/native.ts, identity/src/ed25519/utils.ts, identity/src/utils.ts, identity/test/ed25519.test.ts
Otherwise, use noble implementation. Fixes identity usage in Safari.
In service of #874
Strategy on determining whether to use WebCrypto or noble implementation:
```
// Returns whether ed25519 is supported in Web Crypto API.
// Supported implies:
//
// * WebCrypto ED25519 key implementation supported[1].
// * Can be serialized for IndexedDb[2][3].
// * Uses deterministic signatures as per RFC 8032[4].
//
// * [1] Webkit and Firefox implement WebCrypto (caveats below), and Chrome currently requires
//   "Experimental Web Features" flag enabled for ed25519 keys.
//   https://caniuse.com/mdn-api_subtlecrypto_generatekey_ed25519
// * [2] Firefox supports ed25519 keys, though cannot be serialized (stored in IndexedDB)
//   until v136 https://bugzilla.mozilla.org/show_bug.cgi?id=1939993.
// * …
```
=> fix: Require deterministic signing in the ed25519 WebCrypto implementation

toolshed/routes/frontend/frontend.static.ts
We get a bunch of complaints in Sentry about this unknown mimetype, and it's trivial to avoid for this case.
=> Add mime type for source map files

memory/consumer.ts, runner/src/storage/remote.ts
In some cases, we were using the initial selector of the first query, instead of the version derived from the selection.
When we reconnect, since our remote map can contain the same value more than once, only reconnect each one once.
=> Fix for incorrect subscription to included items.

builder/src/module.ts, builder/src/recipe.ts, builder/test/module.test.ts, builder/test/recipe.test.ts, recipes/recipe.tsx
The extra overloads create difficult to understand type errors + Zod doesn't support `asCell` and so on
=> Remove zod support from builder

background-charm-service/src/env.ts, background-charm-service/src/utils.ts, identity/src/ed25519/index.ts, identity/src/identity.ts, identity/src/index.ts
* Reconfigured Identity to better handle using the fallback (serializable) implementation, allowing `OPERATOR_PASS` to work in the BG service.
* Made `IDENTITY` an optional env var until `OPERATOR_PASS` can be phased out.
=> fix: Use fallback/deserializable key implementation when using passphrase in BG service

runner/src/storage/cache.ts
Fixes how cached provider broadcasts messages.
> Changes to the remote.ts have landed while I was working on the IDB cache and during merge I did not noticed that inspector wiring was different.
=> fix: inspector with new provider

builder/src/types.ts
Still more to do, but at least now everything from storage is automatically compatible with what builder/runner expects. And in the other direction, we wouldn't want it to go without paying attention, but presumably what happens is that the builder type is still used when `[ID]` can't be possible anymore.
Ideally we rename one of these. The builder one is more user-visible, FWIW (but also technically incorrect, so happy to change it to `DataValue` or something like this)
=> harmonize JSONSchema definition with the one from storage

background-charm-service/src/service.ts, background-charm-service/src/space-manager.ts, background-charm-service/src/worker-controller.ts, background-charm-service/src/worker-ipc.ts, background-charm-service/src/worker.ts, identity/src/interface.ts, recipes/rss.tsx
* On (runtime graph) failure, the charm is rescheduled up to 2 more times with a linear backoff. If still unsuccessful, the charm is disabled.
* Disabled tasks do not affect the execution of successfully running tasks.
* Terminal errors (e.g. errors in handling code, or outside of graph execution, like an unhandled rejection) recreate the worker environment.
* TBD if we want to disable all running charms. Due to no longer adhering to execution within a single tick, we cannot trace back failures to a specific charm.
* RSS recipe will now throw (reject) upon failure rather than setting empty items, and be returned in the handler promise chain. Previously, this would be an unhandled rejection.
* Add some types.
=> chore: Rework BG worker failures

charm/src/iframe/static.ts, charm/src/iterate.ts, charm/src/workflow.ts, charm/test/workflow-classification.test.ts, jumble/src/components/CommandCenter.tsx, jumble/src/components/SpecPreview.tsx, jumble/src/components/commands.ts, jumble/src/hooks/use-live-spec-preview.ts, llm/src/index.ts, llm/src/prompts/code-and-schema-gen.ts, llm/src/prompts/spec-and-schema-gen-2.ts
Performs codegen and schema gen in the same pass, with a concise prompt.
This adds a new button to the UI:
You can manually select 'Imagine (Single Phase)' but it will never be picked automatically.
=> Introduce new workflow type `imagine-single-phase`

deno-web-test/browser.ts, deno-web-test/cli.ts, deno-web-test/manifest.ts, deno-web-test/runner.ts, deno-web-test/server.ts
The default port 8000 conflicts with a locally running toolshed. Use a dynamically chosen port so that tests can run concurrently without additional configuration.
=> [deno-web-test] Use a dynamically chosen port

builder/src/env.ts, builder/src/index.ts, charm/src/iterate.ts, jumble/src/components/ActionBar.tsx, jumble/src/components/FeedbackActions.tsx, jumble/src/components/FeedbackDialog.tsx, jumble/src/contexts/ActionManagerContext.tsx, jumble/src/global.d.ts, jumble/src/hooks/use-global-actions.tsx, jumble/src/services/feedback.ts, jumble/src/views/Shell.tsx, jumble/vite.config.ts, llm/src/client.ts, toolshed/env.ts, toolshed/routes/ai/llm/generateText.ts, toolshed/routes/ai/llm/instrumentation.ts, toolshed/routes/ai/llm/llm.handlers.ts, toolshed/routes/ai/llm/llm.index.ts, toolshed/routes/ai/llm/llm.routes.ts
This PR contains all of the API and UI plumbing to handle user feedback submissions for a specific opentelemetry span id (which points to a llm request)
NOTE: This is currently a work-in-progress. We need to figure out how to get the actual llm telemetry span id from the active charm, and I'm not sure how to do this part.
the ui is that we have a feedback button, when you click it, it pops open a thumbs-up and thumbs-down button
when you click a thumbs button, it gives you a text field to fill out some feedback, which we then send to phoenix
this shows up in phoenix as an annotation
=> Llm feedback

jumble/src/components/CharmRunner.tsx, jumble/src/utils/charms.ts
Fixes https://linear.app/common-tools/issue/CT-160/unexpected-refresh-on-charmsspaces-across-tabs by using charmId to track whether to re-render chram view or not.
=> fix: charm reload on charm-list change

charm/src/iterate.ts, charm/src/workflow.ts, jumble/src/components/ActivityStatus.tsx, jumble/src/components/FeedbackActions.tsx, jumble/src/components/Slot.tsx, jumble/src/contexts/ActivityContext.tsx, jumble/src/iframe-ctx.ts, jumble/src/views/Shell.tsx, llm/src/prompts/code-and-schema-gen.ts
* Display an option to upvote/downvote a job with a `llmRequestId`.
* Introduce a composable form of <FeedbackActions> for various button types. Same components used between the primary feedback on main page and individual jobs.
* Add tooltips to activity status and details.
* Introduce a vendored, composable utility <Slot>.
* Remove some animated styles that were causing blinking issues with the nested <FeedbackDialog>.
note there's currently an issue with staging serving the ID, TBD
=> feat: Wire up feedback to activity status jobs

jumble/src/components/CharmRunner.tsx
• On common‑iframe‑error, look up the charm’s LLM trace and send submitFeedback(score = 0, message + stack).
• Falls back gracefully if no trace ID.
• No UI change; only runs when a charm crashes.
=> auto submit feedback on error

toolshed/routes/ai/llm/generateText.ts
They are unsupported, at least currently. See phoenix report: https://phoenix.commontools.dev/projects/UHJvamVjdDo2/spans/b2fa90798de7dbebd8adebcfc54a3d20?selectedSpanNodeId=U3BhbjoxNTQxNTY%3D
Confirmed working locally: 
Happy to merge as-is, just want to confirm this makes sense / I didn't miss anything.
=> Drop `stopSequences` when calling `o3`

background-charm-service/src/worker.ts, charm/src/iterate.ts, jumble/src/main.tsx, runner/src/index.ts, runner/src/recipe-sync.ts, runner/src/runner.ts, runner/src/runtime/console.ts, runner/src/runtime/eval-runtime.ts, runner/src/runtime/index.ts, runner/src/runtime/local-build.ts, runner/src/runtime/runtime.ts, runner/src/scheduler.ts
Adds runtime hooks for intercepting console commands from charms, similar to `onError`, except there can only be one handler at a time. See jumble for a "passthru" implementation. In background workers, messages are annotated with charm ID. In contexts where the runtime is used and no `onConsole` defined, a default passthru implementation is used.
```ts
// Passthru
onConsole(
(
_metadata:
| { charmId?: string; space?: string; recipeId?: string }
| undefined,
_method: ConsoleMethod,
args: any[],
) => {
return args;
},
);
```
Example bg worker log:
```
Worker(did:key:z6Mkh6sEaGxkcq5j9SRofMMCfj1Tg7D1Y5ktVWbgytCpnbYS) Running charm did:key:z6Mkh6sEaGxkcq5j9SRofMMCfj1Tg7D1Y5ktVWbgytCpnbYS/baedreibysswug2cjrqczv3k2vxtzzvbfjfnwjn4lcfb4arulmpb3fleici …
```
=> feat: Enable mapping of console messages from charms

builder/src/recipe.ts, builder/src/types.ts, builder/src/utils.ts
Fixes CT-294
Jordan: Just in case you are curious, this is pretty deep in the recipe stack
=> external references in recipes don't need internal aliases anymore

toolshed/routes/integrations/google-oauth/google-oauth.handlers.ts, toolshed/routes/integrations/google-oauth/google-oauth.utils.ts
The `refresh` handler returns an `OAuth2Tokens`-like object, where the access token is stored as `accessToken`, not `token` like in `AuthData`:
Example response:
```
{
"success": true,
"message": "success",
"tokenInfo": {
"accessToken": "--",
"tokenType": "Bearer",
"expiresIn": 3599,
"scope": [
"https://www.googleapis.com/auth/calendar.readonly",
"https://www.googleapis.com/auth/gmail.readonly",
"https://www.googleapis.com/auth/userinfo.profile",
"https://www.googleapis.com/auth/userinfo.email",
"openid"
],
"refreshToken": "--",
"expiresAt": 1745438821918
}
}
```
In [gmail importer](https://github.com/commontoolsinc/labs/blob/main/recipes/gmail.tsx), we receive the above and fail to retry a request as the response is missing `tokenInfo.token`
=> chore: Serve refresh token as AuthData, not OAuth2Tokens

charm/src/iframe/prompt.ts, charm/src/iterate.ts, charm/src/workflow.ts, llm/src/index.ts, llm/src/options.ts, llm/src/prompts/charm-describe.ts, llm/src/prompts/charm-suggestions.ts, llm/src/prompts/code-and-schema-gen.ts, llm/src/prompts/recipe-fix.ts, llm/src/prompts/spec-and-schema-gen.ts, llm/src/prompts/workflow-classification.ts, runner/src/builtins/llm.ts
An attempt to make threading metadata through the stack a little cleaner, along with apply defaults and using that to pass the `space` in the metadata.
=> Introduce `GenerationOptions` and streamline LLM metadata

charm/src/iframe/static.ts
a well, it will make recipes unsharable in spellbook in the future
=> using import.meta.url breaks deno built recipes

recipes/gmail.tsx
If still unable to request, considered a failure and stop charm.
=> chore: Update gmail recipe to reauth if receiving a 401 and retrying

background-charm-service/src/worker.ts
Objects logs in our dashboard just appear as `{` (maybe systemd is cutting them off?) -- this stringifies logs in the BG worker environment
=> chore: stringify objects logged in the background worker

builder/src/index.ts, builder/src/recipe.ts, builder/src/types.ts, builder/src/utils.ts, charm/src/iterate.ts, jumble/integration/basic-flow.test.ts, jumble/src/recipes/smolIframe.ts, llm/src/prompts/code-and-schema-gen.ts, llm/src/prompts/spec-and-schema-gen.ts, recipes/bgAdmin.tsx, recipes/discord.tsx, recipes/gmail.tsx, recipes/simpleValue.tsx, runner/test/recipes.test.ts, runner/test/schema-lineage.test.ts, utils/deno.json, utils/src/integration.ts, utils/src/types.ts, utils/test/types.test.ts
* Gmail recipe was using `as JSONSchema` rather than `satisfies JSONSchema`, which was causing some type issues
* No strong feelings for naming between `Writable`, `Mutable`, mostly noting distinction
* Pulled in extra `satisfies JSONSchema` clauses from @ubik2  #1103 (without which `Schema` resolves to `any`)
* The `Writable` type helper was not applying mutability recursively; an object with a string type would break out its properties, starting with:
```ts
// via `Schema<typeof EmailSchema>`
type Email = {
readonly id: string;
} & {} & Record<...>
```
but typed as
```ts
// via `Writable<Schema<typeof EmailSchema>>`
type EmailWritable = {
id: Writable<{
toString: () => string;
charAt: (pos: number) => string;
charCodeAt: (index: number) => number;
concat: (...strings: string[]) => …
```
=> chore: Update Writable->Mutable and apply it recursively for queries.

jumble/public/module/charm/sandbox/bootstrap.js
Per https://linear.app/common-tools/issue/CT-308/usedoc-should-return-data-read-from
=> fix: use preloaded data in useDoc

.github/workflows/deno.yml
Switch over to the schema storage type.
This was behind a feature flag to make sure it didn't break anything, but I think this is a reasonable time to get some actual testing.
=> Use the schema storage flag

background-charm-service/src/space-manager.ts, builder/src/types.ts, charm/src/iterate.ts, charm/src/manager.ts, html/deno.jsonc, html/src/path.ts, html/src/render.ts, html/test/assert.ts, iframe-sandbox/src/ipc.ts, jumble/src/iframe-ctx.ts, jumble/src/views/CharmDetailView.tsx, memory/space-schema.ts, memory/traverse.ts, memory/util.ts, runner/src/cfc.ts, runner/src/storage.ts, toolshed/routes/ai/spell/handlers/find-spell-by-schema.ts, toolshed/routes/ai/spell/schema.ts, utils/src/index.ts, utils/src/isObj.ts, utils/src/types.ts
* Align the multiple, slightly different implementations of `isObject` (and `isRecord`) -- sometimes as "non-array" objects, sometimes including arrays, and the differences between `object` and `Record` usage.
* Remove the root entry for `@commontools/utils` (originally tracking down a bug for something pulling in too many modules, but was misleading). Deno requires a root export, so a compile time (no exports) or runtime error fires if doing so to avoid inadvertantly pulling in all utils
---
Standardized all isObject and isRecord checks across the codebase by providing consistent utility functions in utils/types, and removed duplicate or inconsistent implementations.
- **Refactors**
- Replaced custom isObject/isRecord functions with shared versions from utils/types.
- Removed unused or …
=> chore: Align isObject/isRecord usage

html/deno.json, html/src/index.ts, html/src/jsx.ts, html/test/jsx.tsx, jumble/src/components/DitherCube.tsx, recipes/counter.tsx, runner/src/runtime/local-build.ts, ui/src/components/common-fragment.ts, ui/src/components/index.ts
Added support for JSX fragments in the DOM renderer to allow grouping elements without extra nodes.
- **Bug Fixes**
- Updated JSX factory settings and implementation to handle fragments.
- Added tests to verify fragment support.
=> fix: fix html fragment support

runner/src/builtins/llm.ts
Changed the message role assignment so that the first message is always from the user, not the assistant.
=> user should be first

packages/builder/src/module.ts, packages/builder/src/recipe.ts, packages/builder/test/schema-to-ts.test.ts
Fixed type inference for recipes and async lifts to ensure correct types are returned, especially for async functions.
- **Bug Fixes**
- Updated type signatures in recipe and derive to better handle async and nested types.
- Simplified test type checks to reuse declared output structure.
=> fix some inferred types for recipes and async lifts

.gitignore, packages/integration/console.ts, packages/integration/page.ts, packages/jumble/integration/basic-flow.test.ts, packages/seeder/verifier.ts
Tempting to add this automatically to e.g. `.goto(url)`, but there are many reasons the document can reload, so lets make it explicit.
---
Added Page#applyConsoleFormatter to rewrite console methods and ensure objects are stringified in logs during CI and seeder runs.
- **New Features**
- Added applyConsoleFormatter method to Page for better console output.
- Updated tests and seeder to use the new formatter.
=> feat: Introduce Page#applyConsoleFormatter to stringify objects in CI/seeder

recipes/gcal.tsx
Added hangout link and attendees list to the Google Calendar recipe, displaying both in the event table.
- **New Features**
- Shows the hangout link for each event.
- Lists attendee emails for each event.
=> added hangoutlink and attendees list to the gcal recipe

packages/runner/src/scheduler.ts, packages/runner/test/schema.test.ts
so that `idle` can't loop infinitely
---
Ensured the `running` state is always set to undefined before resolving, preventing infinite loops in the `idle` state.
- **Bug Fixes**
- Moved `running = undefined` to reliably clear the state for both sync and async actions.
=> Reliably set `running` to undefined before resolving

packages/cli/cast-recipe.ts, packages/cli/main.ts, packages/cli/name2did.ts
Updated the default operator password in the CLI from "implicit trust" to "common user" to match the jumble naming convention.
=> align space did derivation from name with jumble

packages/builder/src/index.ts, packages/memory/fact.ts, packages/memory/interface.ts, packages/memory/space-schema.ts, packages/memory/space.ts, packages/memory/traverse.ts, packages/runner/src/storage/cache.ts
The two versions of JSONValue had been made similar, but I wanted to just have one version of this type.
---
Replaced duplicate JSONValue type definitions with a single shared version from @commontools/builder to simplify the codebase.
=> Consolidate JSONValue classes

packages/ui/src/components/common-fragment.ts
the this.style would throw an error (try loading the example from recipes), now it doesn't
addresses CT-367
=> style shouldn't be set until after connected

packages/charm/src/manager.ts, packages/runner/src/storage.ts, packages/runner/src/storage/cache.ts
There are a number of other approaches possible here, which can be discussed in CT-399, but this is a minimal fix that doesn't commit to any specific approach.
- I provide the secret classification when loading the charms list
- When we have an error loading a doc, I mark the doc ephemeral and freeze it. This prevents us from saving it or changing it.
- I do a better job comparing the value I'm going to set with the current value, so I don't write `{}` if it was undefined.
Not really part of the core fix, but I also removed the retry and labels from the primary doc write, since these don't belong in there.
Surprisingly, we need the source field from there when it's available.
=> When loading the charm lists, provide the "secret" classification.

packages/background-charm-service/src/worker.ts, packages/charm/src/manager.ts
I should be able to fetch these lists without fetching everything, but currently, I think we do fetch the whole bit.
When I have client side schema traversal, I should be in better shape.
Fixes CT-39
=> Don't run the update for charms that are no longer active

packages/runner/src/builtins/map.ts, packages/runner/test/recipes.test.ts
- handle undefined arrays in map builtin by resetting progress
- add regression test for undefined array input
- `deno task test` in `packages/runner`
- `deno task test` *(fails: could not load packages due to network restrictions)*
=> Fix map with undefined input

packages/charm/src/manager.ts, packages/runner/src/runner.ts
This PR removes a bunch of recipe saving of writing for inner charmlets that doesn't correctly work anyway. Inner charmlets, e.g. those for `.map` calls, work by being spawned by parent charms. That is, we can't correctly rehydrate them individually anyway right now, so let's not also keep storing all these recipes that are at best sometimes working as intended.
Code changes:
* move recipe loading and saving out of runSynced - it now assumes there already is a recipe provided
* move inputs syncing from CharmManager to runSynced
* removed redundant syncRecipe call
* fixed post-run sync call
=> Reduce recipe saving and loading to top-level charms

packages/builder/src/built-in.ts, packages/builder/src/index.ts, packages/runner/src/utils.ts, packages/runner/test/recipes.test.ts
Introduces
```
const newCell = createCell([schema, [name, [initial value]]]);
```
that creates a new cell, which can be returned or assigned to other values. Makes sure they are in their own document, which is useful when confidentiality boundaries are crossed (e.g. make sure sensitive key material is in its own document, separate from other less sensitive data) or to make sure they create referenceable data (by reading with `asCell: true` in a schema) that is for sure detached from its container. 
- `schema` is a schema.
- `name` is used to create a causal id. If omitted, it's by order in the current function (i.e. subsequent calls rely on order not changing to yield the same ids). That's fine in handlers, since each event is a new context anyway, but for lifted functions a name is …
=> Create named cells within lifted functions or handlers

packages/html/src/render.ts
- robustify `bindChildren` in `html` renderer to treat `undefined` or `null` children arrays as empty
- `deno task check` *(fails: No route to host)*
- `deno task test` *(fails: JSR package manifest failed to load)*
=> Handle undefined children in html render

packages/js-runtime/deno.json
These new tests complain on my system if we don't let them access the env.
=> deno test wants env permission for TSC_WATCHFILE

.github/actions/deno-setup/action.yml, .github/workflows/deno.yml, .github/workflows/deploy-production.yml, deno.lock, tasks/check.sh
Some relevant features (via @ubik2):
* With Deno 2.3.x: The new lockfile format includes extra npm package metadata to speed up dependency resolution and installation."
* V8 Insights: https://deno.com/blog/v2.3#v8-js-engine-metrics
=> chore: Update to deno 2.3.5. Reuse CI action.

packages/memory/test/space-test.ts
I saw lots of Cycle Detected messages in the toolshed-staging logs, so suspected that we might not be handling cycles correctly.
However, this unit test logs the cycle once and moves on.
=> Added unit test for a reference cycle

packages/runner/src/query-result-proxy.ts, packages/runner/test/recipes.test.ts
Self-referential data causes issues.
Verified that the creation itself is fine.
Changed `QueryResultProxy` in two ways to improve situation:
1) It now uses a cache to return the exact same object when recursing, so any code that already detects cycles acts correctly
2) throw an error after 100 recursions to at least error more sanely.
=> Fix infinite loop with self-referential data

packages/charm/src/iframe/prompt.ts, packages/charm/src/iframe/static.ts, packages/charm/src/iterate.ts, packages/cli/commands/init.ts, packages/js-runtime/test/runtime.test.ts, packages/js-runtime/test/typescript.compiler.test.ts, packages/js-runtime/utils.ts, packages/runner/src/harness/engine.ts, packages/runner/src/harness/runtime-modules.ts, packages/runner/src/runtime.ts, packages/shell/src/lib/runtime.ts, packages/static/index.ts, packages/static/test/assets.test.ts, packages/toolshed/routes/static/static.index.ts, tasks/build-binaries.ts
Currently, the static asset server is a local file URI (deno) or browser page host. This was working in dev mode in jumble due to the vite proxies (e.g. proxying `localhost:5173` to the toolshed server, hosting static assets). Attempting to reduce the need for a proxy server, this patch adds a static cache to the runtime which is used throughout (mostly for text prompts and TS types), allowing us to thread through the correct location of the static server rather than relying on globals
=> chore: Explicitly require static cache

packages/runner/src/storage/differential.ts, packages/runner/src/storage/transaction/address.ts, packages/runner/src/storage/transaction/chronicle.ts, packages/runner/test/address.test.ts
- Replace path.join('/') with JSON.stringify(path) for consistent serialization
- Update address.toString() to use JSON format for paths
- Fix differential.ts to use Address.toString() instead of manual concatenation
- Update chronicle.ts to use JSON.stringify for path-based map keys
- Ensure consistent path comparison logic across the codebase
This change prevents issues with path elements containing slashes or special characters by using JSON serialization instead of simple string joining.
=> fix(runner): Use JSON.stringify for address path serialization

packages/integration/shell-utils.ts, packages/patterns/integration/counter-operations.test.ts
It surprised me that this didn't work. When we set the counter's value, we do see:
```
Browser Console [warning]: Received update for unknown subscription job:ba4jca3gsgsggq565anzfswbjcd3oc4zugpip4msou7jwlo456awiqm7n
Setting counter value to 42 via direct operation
Browser Console [warning]: Received update for unknown subscription job:ba4jca3gsgsggq565anzfswbjcd3oc4zugpip4msou7jwlo456awiqm7n
Browser Console [warning]: Received update for unknown subscription job:ba4jca3gsgsggq565anzfswbjcd3oc4zugpip4msou7jwlo456awiqm7n
Browser Console [warning]: Received update for unknown subscription job:ba4jca3gsgsggq565anzfswbjcd3oc4zugpip4msou7jwlo456awiqm7n
Browser Console [warning]: Received update for unknown subscription job:ba4jca3gsgsggq565anzfswbjcd3oc4zugpip4msou7jwlo456awiqm7n
Browser …
```
=> Add pattern + testcase to verify live updates [CT-753] [CT-757]

.github/workflows/deno.yml
Reverts commontoolsinc/labs#1669
This didn't help, but did reveal the output is being truncated: https://github.com/commontoolsinc/labs/actions/runs/17138879034/job/48622157261
=> Revert "Capture stdout when running patterns via ansible script"
